Repository openshift/console-operator, pull requests merged in 2018-12, with the labels that each got.

#73 Add block to README for local dev with correct operator token
  README.md
Labels: approved, lgtm, size/M

#72 Update list options for oauth informer
  pkg/console/starter/starter.go
  pkg/console/subresource/oauthclient/oauthclient.go
  pkg/controller/api.go
Labels: approved, lgtm, size/S

#79 Sync loop update
  manifests/05-operator.yaml
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/oauthclient/oauthclient.go
  pkg/console/subresource/secret/secret.go
  pkg/controller/api.go
Labels: approved, lgtm, size/L

#81 Update Deployment sync to check configmap and secret resource versions
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/deployment/deployment.go
Labels: approved, lgtm, size/M

#86 Ensure minimum 2 replicas of console
  examples/cr.yaml
  pkg/console/operator/operator.go
Labels: approved, lgtm, size/S

#80 Fix typos in README
  README.md
Labels: approved, lgtm, size/S

#91 Improve sync loop logging feedback
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/util/util.go
Labels: approved, lgtm, size/M

#92 Add Validate() fn to route
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/route/route.go
Labels: approved, lgtm, size/M

#90 Update boilerplate
  hack/test-unit.sh
  pkg/api/api.go
  pkg/boilerplate/controller/controller.go
  pkg/boilerplate/controller/filter.go
  pkg/boilerplate/controller/option.go
  pkg/boilerplate/controller/sync.go
  pkg/boilerplate/operator/filter.go
  pkg/boilerplate/operator/operator.go
  pkg/boilerplate/operator/option.go
  pkg/boilerplate/operator/sync.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/oauthclient/oauthclient.go
  pkg/console/subresource/route/route.go
  pkg/console/subresource/service/service.go
  pkg/console/subresource/util/util.go
Labels: approved, lgtm, size/XL
