Repository openshift/console-operator, pull requests merged in 2018-10, with the labels that each got.

#32 Adjust OWNERS for console-operator
  OWNERS
Labels: approved, lgtm, size/XS

#30 Update namespace to openshift-console
  pkg/operator/util.go
Labels: approved, lgtm, size/S

#34 Fix CMD in Dockerfile
  Dockerfile
Labels: approved, lgtm, size/XS

#39 Revise root Dockerfile
  Dockerfile
Labels: approved, lgtm, size/M

#41 Add additional labels to Dockerfile
  Dockerfile
Labels: approved, lgtm, size/XS

#42 Update rbac for oauth and route creation
  Dockerfile
  deploy/02-sa.yaml
  deploy/03-rbac-role.yaml
  deploy/04-rbac-rolebinding.yaml
  deploy/05-operator.yaml
Labels: approved, lgtm, size/M

#49 Move /deploy to /manifests, update RBAC rules
  Dockerfile
  manifests/00-crd.yaml
  manifests/00-rbac-role.yaml
  manifests/00-rbac-rolebinding.yaml
  manifests/01-namespace.yaml
  manifests/02-operator.yaml
  manifests/02-sa.yaml
Labels: approved, lgtm, size/M

#51 Add name to log statements
  pkg/operator/configmap.go
  pkg/operator/deployment.go
  pkg/operator/route.go
  pkg/operator/service.go
Labels: approved, lgtm, size/XS

#31 Add LABEL io.openshift.release.operator true in root Dockerfile
  Dockerfile
  manifests/00-crd.yaml
  manifests/01-namespace.yaml
  manifests/02-rbac-role.yaml
  manifests/03-rbac-rolebinding.yaml
  manifests/04-sa.yaml
  manifests/05-operator.yaml
Labels: approved, lgtm, size/S

#54 README updates
  README.md
Labels: approved, lgtm, size/L

#50 Update oauth client to be created via /manifests, but updated via operator
  .gitignore
  examples/cr.yaml
  manifests/00-oauth.yaml
  pkg/operator/configmap.go
  pkg/operator/deployment.go
  pkg/operator/oauth.go
  pkg/operator/reconcile.go
  pkg/operator/route.go
  pkg/operator/service.go
  pkg/stub/handler.go
Labels: approved, lgtm, size/L

#55 Fix typo in README
  README.md
Labels: approved, lgtm, size/XS

#52 Add manifests/image-references file
  manifests/image-references
Labels: approved, lgtm, size/XS

#59 Add ManagementState to handle paused, unpaused, deleted
  examples/cr.yaml
  pkg/apis/console/v1alpha1/types.go
  pkg/operator/configmap.go
  pkg/operator/console.go
  pkg/operator/deployment.go
  pkg/operator/oauth.go
  pkg/operator/reconcile.go
  pkg/operator/route.go
  pkg/operator/service.go
  pkg/operator/util.go
  pkg/stub/handler.go
Labels: approved, lgtm, size/L

#63 Correct image references for origin-console
  examples/cr.yaml
  manifests/05-operator.yaml
  manifests/image-references
  pkg/apis/console/v1alpha1/types.go
  pkg/operator/deployment.go
  pkg/operator/util.go
Labels: approved, lgtm, size/M

#64 Update README.md to reflect current dev practices
  README.md
Labels: approved, lgtm, size/L
