Repository openshift/console-operator, pull requests merged in 2018-11, with the labels that each got.

#65 Add annotation to PodSpec on Deployment whenever ConfigMap changes
  pkg/operator/deployment.go
  pkg/operator/reconcile.go
Labels: approved, lgtm, size/M

#67 Update ClusterOperator to group config.openshift.io
  examples/crd-clusteroperator.yaml
  pkg/operator/operator_status.go
Labels: approved, lgtm, size/S

#68 Status is not namespaced
  examples/crd-clusteroperator.yaml
  pkg/operator/operator_status.go
Labels: approved, lgtm, size/XS

#71 Update README to latest instructions
  README.md
Labels: approved, lgtm, size/L

#75 Use correct informer for OAuth clients
  pkg/console/operator/operator.go
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/M
