Repository openshift/console-operator, pull requests merged in 2019-02, with the labels that each got.

#117 Test editing resources in Managed and Unmanaged console-operator state
  pkg/testframework/framework.go
  test/e2e/main_test.go
  test/e2e/managed_test.go
  test/e2e/removed_test.go
  test/e2e/unmanaged_test.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#123 Correctly sync deployment image
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/configmap/service_ca_test.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/route/route_test.go
  pkg/console/subresource/secret/secret_test.go
  pkg/console/subresource/service/service_test.go
  pkg/console/subresource/util/util.go
  pkg/console/subresource/util/util_test.go
Labels: approved, lgtm, size/L

#125 Moving to use operator v1 api
  examples/cr.yaml
  hack/test-unit.sh
  hack/update-codegen.sh
  manifests/00-crd.yaml
  pkg/apis/console/install.go
  pkg/apis/console/v1/doc.go
  pkg/apis/console/v1/register.go
  pkg/apis/console/v1/types.go
  pkg/apis/console/v1/zz_generated.deepcopy.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/configmap/service_ca.go
  pkg/console/subresource/configmap/service_ca_test.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/route/route.go
  pkg/console/subresource/route/route_test.go
  pkg/console/subresource/secret/secret.go
  pkg/console/subresource/secret/secret_test.go
  pkg/console/subresource/service/service.go
  pkg/console/subresource/service/service_test.go
  pkg/console/subresource/util/util.go
  pkg/console/subresource/util/util_test.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/console/v1/console.go
  pkg/generated/clientset/versioned/typed/console/v1/console_client.go
  pkg/generated/clientset/versioned/typed/console/v1/doc.go
  pkg/generated/clientset/versioned/typed/console/v1/fake/doc.go
  pkg/generated/clientset/versioned/typed/console/v1/fake/fake_console.go
  pkg/generated/clientset/versioned/typed/console/v1/fake/fake_console_client.go
  pkg/generated/clientset/versioned/typed/console/v1/generated_expansion.go
  pkg/generated/informers/externalversions/console/interface.go
  pkg/generated/informers/externalversions/console/v1/console.go
  pkg/generated/informers/externalversions/console/v1/interface.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/listers/console/v1/console.go
  pkg/generated/listers/console/v1/expansion_generated.go
  pkg/testframework/clientset.go
  pkg/testframework/console.go
Labels: approved, lgtm, size/XL

#122 bump: boilerplate
  pkg/boilerplate/controller/controller.go
  pkg/boilerplate/controller/die.go
  pkg/boilerplate/controller/filter.go
  pkg/boilerplate/controller/informer.go
  pkg/boilerplate/controller/option.go
  pkg/boilerplate/controller/sync.go
  pkg/boilerplate/operator/option.go
  pkg/boilerplate/operator/sync.go
Labels: approved, lgtm, size/L

#130 Console Config & Operator Config client additions
  Makefile
  README.md
  hack/test-unit.sh
  hack/update-codegen.sh
  manifests/00-crd-operator-config.yaml
  manifests/02-rbac-role.yaml
  pkg/apis/console/install.go
  pkg/apis/console/v1/doc.go
  pkg/apis/console/v1/register.go
  pkg/apis/console/v1/types.go
  pkg/apis/console/v1/zz_generated.deepcopy.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/configmap/service_ca.go
  pkg/console/subresource/configmap/service_ca_test.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/route/route.go
  pkg/console/subresource/route/route_test.go
  pkg/console/subresource/secret/secret.go
  pkg/console/subresource/secret/secret_test.go
  pkg/console/subresource/service/service.go
  pkg/console/subresource/service/service_test.go
  pkg/console/subresource/util/util.go
  pkg/console/subresource/util/util_test.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/doc.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/doc.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/doc.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/console/v1/console.go
  pkg/generated/clientset/versioned/typed/console/v1/console_client.go
  pkg/generated/clientset/versioned/typed/console/v1/doc.go
  pkg/generated/clientset/versioned/typed/console/v1/fake/doc.go
  pkg/generated/clientset/versioned/typed/console/v1/fake/fake_console.go
  pkg/generated/clientset/versioned/typed/console/v1/fake/fake_console_client.go
  pkg/generated/clientset/versioned/typed/console/v1/generated_expansion.go
  pkg/generated/informers/externalversions/console/interface.go
  pkg/generated/informers/externalversions/console/v1/console.go
  pkg/generated/informers/externalversions/console/v1/interface.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/generated/listers/console/v1/console.go
  pkg/generated/listers/console/v1/expansion_generated.go
  pkg/testframework/clientset.go
  pkg/testframework/console.go
Labels: approved, lgtm, size/XXL

#135 Update README to include updated development instructions
  README.md
  examples/cr-tmp-fake-example.yaml
  examples/cr.yaml
  examples/crd-clusteroperator.yaml
  examples/cvo-manage-operator.yaml
  examples/cvo-unmanange-operator.yaml
  examples/informers-test.yaml
  examples/sync-loop/configmap.yaml
  examples/sync-loop/deployment.yaml
  examples/sync-loop/oauth.yaml
  examples/sync-loop/route.yaml
  examples/sync-loop/secret.yaml
  examples/sync-loop/service.yaml
  hack/build-cross.sh
Labels: approved, lgtm, size/L

#133 Rename Deployment openshift-console to console
  manifests/00-oauth.yaml
  manifests/02-rbac-role.yaml
  pkg/api/api.go
  pkg/console/operator/operator.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/route/route.go
  pkg/console/subresource/route/route_test.go
  pkg/console/subresource/service/service.go
  pkg/console/subresource/service/service_test.go
Labels: approved, lgtm, size/M

#134 Honor configs & report public hostname on status
  manifests/02-rbac-role.yaml
  pkg/api/api.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/testframework/console.go
Labels: approved, lgtm, size/L

#126 Add Goflag option to define branding at build time
  Dockerfile.rhel7
  Makefile
  hack/lib/build/binaries.sh
  hack/lib/constants.sh
  pkg/cmd/version/cmd.go
  pkg/console/subresource/configmap/brand_ocp.go
  pkg/console/subresource/configmap/brand_okd.go
  pkg/console/subresource/configmap/configmap.go
Labels: approved, lgtm, size/M

#141 Update ocp DEFAULT_DOC_URL
  pkg/console/subresource/configmap/brand_ocp.go
Labels: approved, lgtm, size/XS

#143 Fix config singleton names
  pkg/api/api.go
Labels: approved, lgtm, size/XS

#144 List configs by name explicitly
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/S

#145 Public hostname should be the hostname, not URL
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm, size/XS

#153 Use proto kubeconfig instead of kubeconfig
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/XS

#148 Filter route watch to only "console"
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/XS

#156 Increase initial delay of console liveness probe
  pkg/console/subresource/deployment/deployment.go
Labels: approved, lgtm, size/XS

#142 Operator status revisions squash
  manifests/01-oauth.yaml
  manifests/02-namespace.yaml
  manifests/03-rbac-role.yaml
  manifests/04-rbac-rolebinding.yaml
  manifests/05-config.yaml
  manifests/06-sa.yaml
  manifests/07-operator.yaml
  manifests/08-clusteroperator.yaml
  pkg/console/operator/operator.go
  pkg/console/operator/status.go
  pkg/console/operator/sync_v400.go
  pkg/console/operatorclient/operatorclient.go
  pkg/console/starter/starter.go
  pkg/console/subresource/deployment/deployment.go
Labels: approved, lgtm, size/XL

#147 Set console-operator replicas to 1
  manifests/07-operator.yaml
Labels: approved, lgtm, size/XS

#146 Update examples/05-alt-image.yaml to include better dev info
  examples/05-operator-alt-image.yaml
Labels: approved, lgtm, size/S

#161 Restrict console OAuthClient redirect to `/auth/callback` path
  pkg/console/subresource/oauthclient/oauthclient.go
  pkg/console/subresource/oauthclient/oauthclient_test.go
Labels: approved, lgtm, size/XS

#152 Validate URLs from the CR file and additional unit tests for ocp tag
  examples/cr-console.operator.config.yaml
  hack/test-unit.sh
  manifests/00-crd-operator-config.yaml
  pkg/console/subresource/configmap/configmap_test.go
Labels: approved, lgtm, size/M

#165 Validate properties in CRD
  manifests/00-crd-operator-config.yaml
Labels: approved, lgtm, size/S

#160 Change unit test to use cleaner error output
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/configmap/service_ca_test.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/oauthclient/oauthclient_test.go
  pkg/console/subresource/route/route_test.go
  pkg/console/subresource/secret/secret_test.go
  pkg/console/subresource/service/service_test.go
  pkg/console/subresource/util/util_test.go
Labels: approved, lgtm, size/L
