Repository openshift/console-operator, pull requests merged in 2019-07, with the labels that each got.

#252 Add `nodeSelector` to downloads deployment
  manifests/07-downloads-deployment.yaml
Labels: approved, lgtm, size/XS

#254 Add proxy support
  manifests/03-rbac-role-cluster.yaml
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, lgtm, size/M

#255 Add applicationMenu to ConsoleLink CRD
  manifests/00-crd-extension-console-link.yaml
Labels: approved, lgtm, size/S

#246 Add console extension manfiest for ConsoleExternalLogLinks CRD
  manifests/00-crd-extension-console-log-link.yaml
  manifests/03-rbac-role-cluster-extensions.yaml
Labels: approved, lgtm, size/M

#257 Set statuspage-id flag
  pkg/console/subresource/deployment/deployment.go
Labels: approved, lgtm, size/M

#258 Add e2e test to test if --statuspage-id flag was set on console's pod template
  test/e2e/providers_test.go
Labels: approved, lgtm, size/M

#256 Adding build support for archs other than amd64
  Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#263 Remove old dev scripts
  dev_delete_all.sh
  dev_deploy_all.sh
  dev_run_local.sh
  dev_test_sync_loop.sh
Labels: approved, lgtm, size/L
