Repository openshift/console-operator, pull requests merged in 2019-04, with the labels that each got.

#190 Fix imports in starter.go
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/S

#189 Simplify SyncSecret()
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm, size/S

#193 Remove ApplyRoute() func
  pkg/console/subresource/route/route.go
Labels: approved, lgtm, size/M

#183 Select host from admitted ingress, else fall back to route.spec.host
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/oauthclient/oauthclient.go
  pkg/console/subresource/oauthclient/oauthclient_test.go
  pkg/console/subresource/route/route.go
Labels: approved, lgtm, size/L

#196 Lowering capital letter for logrus and fmt messages
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/deployment/deployment.go
Labels: approved, lgtm, size/S

#198 report last few log lines as error
  manifests/07-downloads-deployment.yaml
  manifests/07-operator.yaml
  pkg/console/subresource/deployment/deployment.go
Labels: approved, lgtm, size/XS

#180 Revise branding mechanism for Console Operator
  Dockerfile
  manifests/03-rbac-role-ns-openshift-config-managed.yaml
  manifests/04-rbac-rolebinding.yaml
  pkg/api/api.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
Labels: approved, lgtm, size/L

#200 Fix typo completele/complete
  pkg/console/operator/operator.go
Labels: approved, lgtm, size/XS

#201 Switch doc links to version 4.1
  pkg/console/subresource/configmap/brand_ocp.go
  pkg/console/subresource/configmap/brand_okd.go
  pkg/console/subresource/configmap/configmap_test.go
Labels: approved, lgtm, size/S

#202 Change default api value to v1
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
Labels: approved, lgtm, size/S

#203 Update SyncRoute() to look for host on ingress, not route.spec.host
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/route/route.go
Labels: approved, lgtm, size/S

#204 pkg/console/subresource/deployment: Fix "avalable" -> "available" typo
  pkg/console/subresource/deployment/deployment.go
Labels: approved, lgtm, size/XS

#209 Add `release.openshift.io/create-only` annotation to OAuthClient
  manifests/01-oauth.yaml
Labels: approved, lgtm, size/XS

#210 Remove version-mapping config map
  manifests/05-version-mapping.yaml
Labels: approved, lgtm, size/XS

#207 Bump * (transition status: failing to degraded)
  glide.lock
  pkg/console/operator/operator.go
  pkg/console/operator/status.go
  pkg/testframework/framework.go
  test/e2e/unmanaged_test.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_test.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/label.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/XXL

#195 Improve Status:Available & improve logging
  pkg/console/errors/sync_errors.go
  pkg/console/operator/operator.go
  pkg/console/operator/status.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/oauthclient/oauthclient.go
  pkg/console/subresource/route/route.go
  pkg/testframework/framework.go
  test/e2e/managed_test.go
  test/e2e/removed_test.go
  test/e2e/unmanaged_test.go
Labels: approved, lgtm, size/XL

#208 Reduce default log level
  manifests/07-operator.yaml
Labels: approved, lgtm, size/XS

#214 Add node-selector annotation to namespace
  manifests/02-namespace.yaml
Labels: size/XS

#206 e2e tests for LogLevel
  pkg/console/subresource/deployment/deployment.go
  pkg/testframework/console-operator.go
  pkg/testframework/framework.go
  test/e2e/logging_test.go
  test/e2e/managed_test.go
  test/e2e/removed_test.go
  test/e2e/unmanaged_test.go
Labels: approved, lgtm, size/L

#213 Delete service-ca configmap when ManagementState:Removed
  pkg/console/operator/operator.go
Labels: approved, lgtm, size/XS

#216 Remove noisy print
  pkg/testframework/framework.go
Labels: approved, lgtm, size/XS
