Repository openshift/console-operator, pull requests merged in 2019-01, with the labels that each got.

#96 Inject service-ca.crt into the console pod from a config map
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/service_ca.go
  pkg/console/subresource/deployment/deployment.go
Labels: approved, lgtm, size/L

#104 Update operator replicas to 3
  manifests/05-operator.yaml
Labels: approved, lgtm, size/XS

#107 Console operator e2e test - Managed state
  hack/test-e2e.sh
  pkg/api/api.go
  pkg/testframework/clientset.go
  pkg/testframework/config.go
  pkg/testframework/framework.go
  test/e2e/main_test.go
  test/e2e/managed_test.go
Labels: approved, lgtm, size/L

#102 Add node selector to operator deployment to deploy on master node
  manifests/05-operator.yaml
Labels: approved, lgtm, size/XS

#88 Add Resource Limits to Deployment
  manifests/05-operator.yaml
  pkg/console/subresource/deployment/deployment.go
Labels: approved, lgtm, size/S

#111 Set a 10m CPU request for console operator and console
  manifests/05-operator.yaml
  pkg/console/subresource/deployment/deployment.go
Labels: approved, lgtm, size/XS

#110 Reduce Operator & Console replicas to 2 each
  examples/cr.yaml
  manifests/05-operator.yaml
  pkg/console/operator/operator.go
Labels: approved, lgtm, size/S

#112 Add e2e test for console operator Unmanaged and Removed states
  pkg/api/api.go
  pkg/testframework/clientset.go
  pkg/testframework/console.go
  pkg/testframework/framework.go
  pkg/testframework/logs.go
  test/e2e/managed_test.go
  test/e2e/removed_test.go
  test/e2e/unmanaged_test.go
Labels: approved, lgtm, size/L

#116 Move console operator into a separate namespace
  README.md
  examples/05-operator-alt-image.yaml
  manifests/01-namespace.yaml
  manifests/02-rbac-role.yaml
  manifests/03-rbac-rolebinding.yaml
  manifests/04-config.yaml
  manifests/04-sa.yaml
  manifests/05-operator.yaml
  pkg/api/api.go
  pkg/testframework/console.go
  pkg/testframework/framework.go
Labels: approved, lgtm, size/L

#109 Unit tests Console Operator
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/configmap/service_ca_test.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/oauthclient/oauthclient_test.go
  pkg/console/subresource/route/route_test.go
  pkg/console/subresource/secret/secret_test.go
  pkg/console/subresource/service/service_test.go
  pkg/console/subresource/util/util_test.go
Labels: approved, lgtm, size/XXL
