Repository openshift/console-operator, pull requests merged in 2019-08, with the labels that each got.

#262 Add ClusterOperatorLoggingController
  pkg/api/api.go
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/XS

#259 Remove LastTransitionTime from status.conditions
  pkg/console/operator/status.go
Labels: approved, lgtm, size/L

#266 Add group to managed and umanaged ClusterVersion overrides
  examples/console-client-secret
  examples/cvo-manage-operator.yaml
  examples/cvo-unmanage-operator.yaml
Labels: approved, lgtm, size/XS

#267 Bug 1739312: Update doc URL to 4.2
  pkg/console/subresource/configmap/brand_ocp.go
  pkg/console/subresource/configmap/brand_okd.go
  pkg/console/subresource/configmap/configmap_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#261 Add ManagementStateController
  pkg/console/operator/operator.go
  pkg/console/operator/status.go
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/M

#269 Add condition handlers, implement for Degraded prefixing, add StaleConditionController
  pkg/console/operator/operator.go
  pkg/console/operator/status.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  test/e2e/framework/console-operator.go
Labels: approved, lgtm, size/L

#271 Update Progressing condition to use handler
  pkg/console/operator/status.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  test/e2e/framework/console-operator.go
Labels: approved, lgtm, size/L

#272 Update Available condition to use handlers
  pkg/console/operator/status.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/deployment/deployment.go
  test/e2e/framework/console-operator.go
Labels: approved, lgtm, size/L

#253 Bug 1724977: Invalid customization values should not make operator hotloop
  pkg/console/operator/operator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#265 Add support for proxies TrustedCA
  pkg/api/api.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/trusted_ca.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, lgtm, size/XL

#275 Bug 1745772: manifests/07-downloads-deployment: Exec Python for signal handling
  manifests/07-downloads-deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#276 Bug 1737315: Fix secret in pod log
  glide.lock
  vendor/github.com/go-test/deep/CHANGES.md
  vendor/github.com/openshift/api/apps/v1/generated.pb.go
  vendor/github.com/openshift/api/authorization/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/oauth/v1/generated.pb.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/generated.pb.go
  vendor/github.com/openshift/api/quota/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/template/v1/generated.pb.go
  vendor/github.com/openshift/api/user/v1/generated.pb.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/library-go/Makefile
  vendor/github.com/openshift/library-go/alpha-build-machinery/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/operator/doc.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/scripts/doc.go
  vendor/github.com/openshift/library-go/cmd/crd-schema-gen/generator/generator.go
  vendor/github.com/openshift/library-go/cmd/crd-schema-gen/main.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/oauth/oauthserviceaccountclient/oauthclientregistry_test.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client_test.go
  vendor/github.com/openshift/library-go/pkg/operator/watchdog/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/watchdog/cmd_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#274 Bug 1740387: Better Progressing & Degraded condition handling & names
  pkg/console/operator/operator.go
  pkg/console/operator/status.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/route/route.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#277 Add proxy config to ClusterOperator status related objects
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/XS

#279 Use api's ConfigResourceName variable instead the plain string
  pkg/console/operator/operator.go
Labels: approved, lgtm, size/XS

#283 Bug 1746966: manifests/07-downloads-route: Set redirect termination
  manifests/07-downloads-route.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#281 manifests/07-downloads-deployment: Add container probes
  manifests/07-downloads-deployment.yaml
Labels: approved, lgtm, size/S

#282 Bug 1745772: manifests/07-downloads-deployment: Set terminationGracePeriodSeconds
  manifests/07-downloads-deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#280 Bug 1746925: Custom logo file cant be found when SVG
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/brand_custom_logo.go
  pkg/console/subresource/configmap/brand_custom_logo_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
