Repository openshift/console-operator, pull requests merged in 2019-05, with the labels that each got.

#218 Add public console config to publish console URL
  manifests/03-rbac-role-ns-openshift-config-managed.yaml
  manifests/04-rbac-rolebinding.yaml
  manifests/08-config-public.yaml
  pkg/api/api.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/configmap/service_ca.go
  pkg/console/subresource/configmap/service_ca_test.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/testframework/framework.go
Labels: approved, lgtm, size/L

#222 Check if OAuth is already updated when in Removed state to prevent hotloop
  pkg/console/operator/operator.go
Labels: approved, lgtm, size/XS

#224 Fix tolerations
  manifests/07-downloads-deployment.yaml
  manifests/07-operator.yaml
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, lgtm, size/M

#211 Use CVO to create operator config
  manifests/01-operator-config.yaml
  manifests/07-operator.yaml
  pkg/cmd/operator/cmd.go
  pkg/console/operator/operator.go
Labels: approved, lgtm, size/M

#226 Bug 1707478: Reorder manifests to ensure ClusterOperator is last
  manifests/05-config-public.yaml
  manifests/07-downloads-route.yaml
  manifests/07-downloads-service.yaml
Labels: approved, lgtm, size/XS

#221 e2e tests setup refactoring
  test/e2e/logging_test.go
  test/e2e/managed_test.go
  test/e2e/unmanaged_test.go
Labels: approved, lgtm, size/M

#228 Refactor priotrity of config maps for console
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
Labels: approved, lgtm, size/L

#230 manifests: add resource requests to downloads pod
  manifests/07-downloads-deployment.yaml
Labels: approved, lgtm, size/XS

#231 Bump to Go 1.12
  Dockerfile
  Dockerfile.rhel7
  README.md
  hack/test-e2e.sh
  hack/verify-govet.sh
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/service_ca_test.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/route/route_test.go
Labels: approved, lgtm, size/M
