Repository openshift/console-operator, pull requests merged in 2019-03, with the labels that each got.

#166 Bug 1684805: Set priority class on console and console operator pods
  manifests/07-operator.yaml
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, lgtm, size/XS

#167 Bug 1685233: Switch to `imagePullPolicy: IfNotPresent`
  manifests/07-operator.yaml
Labels: approved, lgtm, size/XS

#169 Bug 1686133: Fix operator availability to include route availability check
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/route/route.go
Labels: approved, lgtm, size/M

#171 Add unit tests for deployment IsReady() func
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, lgtm, size/M

#170 Add test for route IsAdmitted()
  pkg/console/subresource/route/route_test.go
Labels: approved, lgtm, size/L

#172 Update README
  README.md
  examples/07-operator-alt-image.yaml
  examples/cvo-unmanage-operator.yaml
Labels: approved, lgtm, size/XS

#173 Fix missing masterPublicURL on console configmap
  manifests/03-rbac-role.yaml
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
Labels: approved, lgtm, size/L

#168 Report Operand version
  manifests/05-version-mapping.yaml
  manifests/07-operator.yaml
  manifests/08-clusteroperator.yaml
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, lgtm, size/L

#176 Fix route admission log message
  pkg/console/subresource/route/route.go
Labels: approved, lgtm, size/XS

#178 Bug 1689773: Set proper status when console route is not admitted
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm, size/S

#177 manifests: Serve oc from within the cluster
  manifests/07-downloads-deployment.yaml
  manifests/08-downloads-service.yaml
  manifests/09-downloads-route.yaml
  manifests/image-references
Labels: approved, lgtm, size/L

#181 Remove duplicate import
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm, size/XS

#182 Remove unused sync funcs
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm, size/S

#186 Fix Sprintf "deployment" for SyncDeployment() error
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm, size/XS

#179 Handle Console Operator LogLevel
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, lgtm, size/M

#185 Add infrastructures config to operator related objects
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/XS

#184 Use const in configmap test, eliminate stale comments
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap_test.go
Labels: approved, lgtm, size/S

#162 Support Spec.UnsupportedConfigOverrides
  pkg/console/operator/status.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
Labels: approved, lgtm, size/L

#187 Remove hardcoded amd64 from Dockerfile for MultiArch builds
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#188 Split roles into 3 files for clarity & to avoid mistakes
  manifests/03-rbac-role-cluster.yaml
  manifests/03-rbac-role-ns-console.yaml
  manifests/03-rbac-role-ns-operator.yaml
  manifests/03-rbac-role.yaml
Labels: approved, lgtm, size/L
