Repository openshift/console-operator, pull requests merged in 2019-06, with the labels that each got.

#212 E2E test specific to branding
  test/e2e/branding_test.go
  test/e2e/logging_test.go
Labels: approved, lgtm, size/L

#232 Remove unused hack/ scripts
  Makefile
  hack/build-cross.sh
  hack/build-images.sh
  hack/build-rpms.sh
  hack/cherry-pick.sh
  hack/move-upstream.sh
  hack/push-release.sh
  hack/update-generated-bindata.sh
  hack/verify-generated-bindata.sh
  hack/verify-upstream-commits.sh
Labels: approved, lgtm, size/XL

#234 Add providers with statuspage.io to operator config
  manifests/00-crd-operator-config.yaml
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  test/e2e/providers_test.go
Labels: approved, lgtm, size/L

#227 Replace logrus with klog
  pkg/console/operator/operator.go
  pkg/console/operator/status.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/route/route.go
  pkg/console/subresource/util/util.go
Labels: approved, lgtm, size/L

#237 Update example operator yaml with alt image
  examples/07-operator-alt-image.yaml
Labels: approved, lgtm, size/XS

#238 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#239 Improve cluster operator status reporting during upgrades
  pkg/console/operator/status.go
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm, size/S

#235 Configmap/builder
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/config_merger.go
  pkg/console/subresource/consoleserver/config_merger_test.go
Labels: approved, lgtm, size/XXL

#241 Add WaitForSettledState func to check Operator Config before progressing
  pkg/testframework/console-operator.go
  test/e2e/branding_test.go
  test/e2e/logging_test.go
  test/e2e/managed_test.go
  test/e2e/providers_test.go
  test/e2e/removed_test.go
  test/e2e/unmanaged_test.go
Labels: approved, lgtm, size/M

#243 Promote sync() funcs to methods on the operator
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm, size/L

#244 Rename consoleserver/config.go to consoleserver/types.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/types.go
Labels: approved, lgtm, size/XS

#229 Add console extension manifests
  manifests/00-crd-extension-console-cli-download.yaml
  manifests/00-crd-extension-console-link.yaml
  manifests/00-crd-extension-console-notification.yaml
  manifests/03-rbac-role-cluster-extensions.yaml
  manifests/04-rbac-rolebinding-cluster.yaml
Labels: approved, lgtm, size/L

#245 Custom brand revisions
  manifests/03-rbac-role-ns-openshift-config.yaml
  manifests/04-rbac-rolebinding.yaml
  pkg/api/api.go
  pkg/console/clientwrapper/without_secret.go
  pkg/console/errors/custom_logo_errors.go
  pkg/console/errors/custom_logo_errors_test.go
  pkg/console/operator/operator.go
  pkg/console/operator/status.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/brand_custom_logo.go
  pkg/console/subresource/configmap/brand_custom_logo_test.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  test/e2e/brand_customization_test.go
  test/e2e/branding_test.go
Labels: approved, lgtm, size/XL

#247 Update link location pattern regex
  manifests/00-crd-extension-console-link.yaml
Labels: approved, lgtm, size/XS

#249 Allow custom-logo configmap to be removed
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/brand_custom_logo.go
  pkg/console/subresource/configmap/brand_custom_logo_test.go
Labels: approved, lgtm, size/M
