Repository openshift/console-operator, pull requests merged in 2019-10, with the labels that each got.

#304 Fix NO_PROXY flake
  test/e2e/proxy_test.go
Labels: approved, lgtm, size/M

#302 Remove extensions CRDs to migrate to openshift-config-operator
  manifests/00-crd-extension-console-cli-download.yaml
  manifests/00-crd-extension-console-link.yaml
  manifests/00-crd-extension-console-log-link.yaml
  manifests/00-crd-extension-console-notification.yaml
Labels: approved, lgtm, size/L

#308 manifests/07-downloads-deployment: Catch and exit on TERM
  manifests/07-downloads-deployment.yaml
Labels: approved, lgtm, size/XS

#309 Make status handlers standalone helper funcs
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/status/status.go
  pkg/console/status/status_test.go
Labels: approved, lgtm, size/M

#310 Reorganize args to NewConsoleOperator func
  pkg/console/operator/operator.go
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/M

#311 Remove unused argument
  pkg/console/operator/operator.go
Labels: approved, lgtm, size/XS

#314 Temporarily return extension CRDs from cluster-config-operator to our Manifests dir
  manifests/00-crd-consoleclidownloads.yaml
  manifests/00-crd-consoleexternalloglinks.yaml
  manifests/00-crd-consolelinks.yaml
  manifests/00-crd-consolenotifications.yaml
  manifests/00-crd-consoleyamlsamples.yaml
Labels: approved, lgtm, size/L

#306 Add ConsoleCliDownloads controller
  hack/test-unit.sh
  manifests/03-rbac-role-cluster-extensions.yaml
  manifests/03-rbac-role-cluster.yaml
  pkg/api/api.go
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/clidownloads/controller_test.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/L

#305 NewServiceSyncController
  pkg/console/controllers/service/controller.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/L

#324 Bug 1764227: Incorrect validation pattern on ConsoleCLIDownloads Href field
  manifests/00-crd-extension-console-cli-download.yaml
  manifests/00-crd-extension-console-link.yaml
  manifests/00-crd-extension-console-notification.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS
