Repository openshift/console-operator, pull requests merged in 2019-11, with the labels that each got.

#318 Add e2e test for oc and odo ConsoleCLIDownloads CRs
  pkg/api/api.go
  pkg/console/controllers/clidownloads/controller.go
  test/e2e/framework/clientset.go
  test/e2e/framework/console-operator.go
  test/e2e/framework/framework.go
  test/e2e/managed_test.go
  test/e2e/unmanaged_test.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#333 Skip Unmanaged and Removed TCs
  test/e2e/removed_test.go
  test/e2e/unmanaged_test.go
Labels: approved, lgtm, size/XS

#335 Bug 1767926: Bump vendor
  glide.lock
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/console/v1/0000_10_consoleyamlsample.crd.yaml
  vendor/github.com/openshift/api/console/v1/types_console_yaml_sample.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-svcat-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/github.com/openshift/api/quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  vendor/github.com/openshift/api/quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml-merge-patch
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/template/v1/generated.proto
  vendor/github.com/openshift/api/template/v1/types.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/inprocess.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/inprocess_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/kubestorageversionmigrator.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/types.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/testing/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/events/eventstesting/recorder_wrapper.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#337 Bug 1768542: Bump deps
  glide.lock
  vendor/github.com/openshift/api/console/v1/0000_10_consoleyamlsample.crd.yaml
  vendor/github.com/openshift/api/console/v1/types_console_yaml_sample.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#338 Missing service informer
  pkg/console/controllers/service/controller.go
  pkg/console/starter/starter.go
  test/e2e/framework/console-operator.go
  test/e2e/framework/utils.go
  test/e2e/removed_test.go
  test/e2e/unmanaged_test.go
Labels: approved, lgtm, size/M

#330 Improve deployment state errors
  pkg/console/subresource/deployment/deployment.go
Labels: approved, lgtm, size/M

#339 Refactor logging
  test/e2e/brand_builtins_test.go
  test/e2e/framework/console-operator.go
Labels: approved, lgtm, size/S

#340 Unify testing resources in e2e tests
  test/e2e/framework/framework.go
Labels: approved, lgtm, size/M

#342 Remove proxyConfig NotFound check
  pkg/console/operator/operator.go
Labels: approved, lgtm, size/XS

#328 Bug 1764704: Sync router-ca to the console namespace
  hack/test-unit.sh
  pkg/api/api.go
  pkg/console/controllers/resourcesyncdestination/controller.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#299 Bug 1764313: 4.3 console_url is no longer reported on metrics endpoint (fix, with e2e test)
  pkg/console/metrics/metrics.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  test/e2e/framework/config.go
  test/e2e/framework/framework.go
  test/e2e/metrics_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#349 Cleanup disorganized imports in sync_v400.go
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm, size/XS

#348 Remove redundant service delete
  pkg/console/operator/operator.go
Labels: approved, lgtm, size/XS

#345 Add CRUD (create,delete) tests for console extension resources
  test/e2e/extensions_crud_test.go
  test/e2e/framework/clientset.go
Labels: approved, lgtm, size/L

#344 Add e2e test for oc downloads links
  test/e2e/downloads_test.go
  test/e2e/framework/framework.go
  test/e2e/metrics_test.go
  test/e2e/removed_test.go
  test/e2e/util_http.go
Labels: approved, lgtm, size/L

#347 Add liveness and readiness probes to console operator
  manifests/07-operator.yaml
Labels: approved, lgtm, size/S

#351 Bug 1773431: Update doc link for 4.3
  pkg/console/subresource/configmap/brand_ocp.go
  pkg/console/subresource/configmap/brand_okd.go
  pkg/console/subresource/configmap/configmap_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#346 Bug 1768684: Avoid console_url metric as empty string
  pkg/console/metrics/console_url.go
  pkg/console/metrics/register.go
  pkg/console/operator/sync_v400.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#343 Enable multi-arch support in downloads
  manifests/07-downloads-deployment.yaml
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/clidownloads/controller_test.go
  test/e2e/downloads_test.go
Labels: approved, lgtm, ok-to-test, size/M

#353 pkg/console/controllers/clidownloads/controller: Arch qualifiers for Mac/Windows
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/clidownloads/controller_test.go
Labels: approved, lgtm, size/XS
