Repository openshift/console-operator, pull requests merged in 2019-12, with the labels that each got.

#355 bug 1772759: fix console operator panic when RouterCAValidationDegraded
  hack/test-unit.sh
  pkg/api/api.go
  pkg/console/controllers/resourcesyncdestination/controller.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#356 Remove stale conditions from RemoveStaleConditionsController()
  pkg/console/starter/starter.go
Labels: approved, lgtm, size/M

#352 Bug 1773808: Enable multi-arch support in downloads [4.2]
  manifests/07-downloads-deployment.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/XS

#361 Sync default-ingress-cert to the console namespace
  hack/test-unit.sh
  pkg/api/api.go
  pkg/console/controllers/resourcesyncdestination/controller.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, lgtm, size/L
