Repository openshift/console-operator, pull requests merged in 2019-09, with the labels that each got.

#285 Handle error by proper status condition
  pkg/console/operator/status.go
Labels: approved, lgtm, size/XS

#287 Add unit tests for condition handlers
  pkg/console/operator/status_test.go
Labels: approved, lgtm, size/L

#289 Make sure configMap with custom logo is created before mount
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm, size/M

#291 Get correct ConfigMap name in e2e test helper
  test/e2e/framework/framework.go
Labels: approved, lgtm, size/XS

#292 Bug 1750790: Revert "Make sure configMap with custom logo is created before mount"
  pkg/console/operator/sync_v400.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#293 Fix custom-logo e2e test
  test/e2e/brand_customization_test.go
Labels: approved, lgtm, size/M

#294 Update TestCustomBrand e2e test
  test/e2e/brand_customization_test.go
Labels: approved, lgtm, size/L

#295 manifests/07-downloads-deployment: Serve from cli-artifacts
  manifests/07-downloads-deployment.yaml
  manifests/07-operator.yaml
  manifests/image-references
Labels: approved, lgtm, size/M

#270 Expose metrics
  manifests/0000_90_console-operator_01_prometheusrbac.yaml
  manifests/0000_90_console-operator_02_servicemonitor.yaml
  manifests/02-namespace.yaml
  manifests/04-rbac-rolebinding-cluster.yaml
  manifests/04-rbac-rolebinding.yaml
  manifests/05-config.yaml
  manifests/05-service.yaml
  manifests/07-operator.yaml
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm, size/L

#297 Bug 1753672: Redeploy console deployment upon proxy changes
  pkg/console/operator/operator.go
  pkg/console/starter/starter.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#298 Update operator for project link API changes
  manifests/00-crd-extension-console-link.yaml
Labels: approved, lgtm, size/S

#296 Proxy e2e test
  test/e2e/framework/clientset.go
  test/e2e/framework/framework.go
  test/e2e/framework/utils.go
  test/e2e/proxy_test.go
Labels: approved, lgtm, size/L
