Repository openshift/console-operator, pull requests merged in 2020-10, with the labels that each got.

#470 Bug 1880307: Bump k8s vendors to 1.18.9. to fix bug in reflector not recovering from 'Too large resource version'
  Dockerfile.rhel7
  go.mod
  go.sum
  pkg/console/operatorclient/operatorclient.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#476 Updating openshift-enterprise-console-operator builder & base images to be consistent with ART
  Dockerfile.rhel7
Labels: approved, lgtm

#477 add current profile annotations to CVO manifests
  manifests/0000_90_console-operator_01_prometheusrbac.yaml
  manifests/0000_90_console-operator_02_servicemonitor.yaml
  manifests/01-helm.yaml
  manifests/01-oauth.yaml
  manifests/01-operator-config.yaml
  manifests/02-namespace.yaml
  manifests/03-rbac-role-cluster-extensions.yaml
  manifests/03-rbac-role-cluster.yaml
  manifests/03-rbac-role-ns-console.yaml
  manifests/03-rbac-role-ns-openshift-config-managed.yaml
  manifests/03-rbac-role-ns-openshift-config.yaml
  manifests/03-rbac-role-ns-operator.yaml
  manifests/04-rbac-rolebinding-cluster.yaml
  manifests/04-rbac-rolebinding.yaml
  manifests/05-config-public.yaml
  manifests/05-config.yaml
  manifests/05-service.yaml
  manifests/06-sa.yaml
  manifests/07-downloads-deployment.yaml
  manifests/07-downloads-helm.yaml
  manifests/07-downloads-route.yaml
  manifests/07-downloads-service.yaml
  manifests/07-operator.yaml
  manifests/08-clusteroperator.yaml
  manifests/09-console-link-openshift-blog.yaml
  manifests/09-console-link-openshift-learning-portal.yaml
Labels: approved, lgtm

#250 CONSOLE-1523: Change log level values to use klog types
  pkg/console/subresource/deployment/deployment.go
Labels: approved, lgtm, size/S
