Repository openshift/console-operator, pull requests merged in 2020-01, with the labels that each got.

#362 Bug 1784582: Added Helm CLI download links
  manifests/07-downloads-helm.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#364 Update doc link to 4.4
  pkg/cmd/version/cmd.go
  pkg/console/subresource/configmap/brand_ocp.go
  pkg/console/subresource/configmap/brand_okd.go
  pkg/console/subresource/configmap/configmap_test.go
Labels: approved, lgtm, size/S

#366 RBAC for console backend to request openshift-config-managed configmaps
  manifests/03-rbac-role-ns-openshift-config-managed.yaml
  manifests/04-rbac-rolebinding.yaml
  manifests/06-sa.yaml
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, lgtm, size/M

#371 manifests: allow console service account to list managed configmaps
  manifests/03-rbac-role-ns-openshift-config-managed.yaml
Labels: approved, lgtm, size/XS

#369 Bug 1783163: fix RBAC for ConsoleYAMLSample
  manifests/03-rbac-role-cluster-extensions.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#375 Bug 1794546: Console-1933: IPv6 support (simpler alternative)
  manifests/05-config.yaml
  manifests/07-downloads-deployment.yaml
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/config_merger_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
