Repository openshift/console-operator, pull requests merged in 2020-08, with the labels that each got.

#454 Bug 1856667: Bump DEFAULT_DOC_URL for okd & ocp
  pkg/console/subresource/configmap/brand_ocp.go
  pkg/console/subresource/configmap/brand_okd.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#455 Allow console service account to read HelmChartRepository CR
  manifests/03-rbac-role-cluster.yaml
  manifests/03-rbac-role-ns-openshift-config.yaml
  manifests/04-rbac-rolebinding.yaml
Labels: approved, lgtm

#456 Revert "Allow console service account to read HelmChartRepository CR"
  manifests/03-rbac-role-cluster.yaml
  manifests/03-rbac-role-ns-openshift-config.yaml
  manifests/04-rbac-rolebinding.yaml
Labels: approved, lgtm

#457 Bug 1859331: manifests/07-downloads-deployment: Create index.html
  manifests/07-downloads-deployment.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#463 Bug 1873414: Move deployment script to python3
  manifests/07-downloads-deployment.yaml
Labels: bugzilla/severity-urgent, bugzilla/valid-bug

#464 Bug 1859331: Fix downloads index
  manifests/07-downloads-deployment.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#459 Bug 1870514: Configuring custom certificate for default console route
  pkg/console/controllers/route/controller.go
  pkg/console/subresource/route/route.go
  pkg/console/subresource/route/route_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
