Repository openshift/console-operator, pull requests merged in 2020-05, with the labels that each got.

#420 Bug 1826873: Default console route should redirect to correct public URL when route hostname has been customized
  pkg/api/api.go
  pkg/console/controllers/route/controller.go
  pkg/console/controllers/service/controller.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/types.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/route/route.go
  pkg/console/subresource/route/route_test.go
  pkg/console/subresource/service/service.go
  pkg/console/subresource/service/service_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#416 Bug 1829236: CustomURL e2e
  test/e2e/custom_url_test.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#424 Bug 1830809: Use helperv1.UpdateStatus() for updating operators status
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/route/controller.go
  pkg/console/controllers/service/controller.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/status/status.go
  pkg/console/status/status_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#428 Bug 1835337: Update CLI download page text for odo
  pkg/console/controllers/clidownloads/controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#425 Bug 1833465: Updating operator status - cleanUp
  pkg/console/operator/sync_v400.go
  pkg/console/status/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#426 Bug 1834222: Check for custom console route hostname not to be the same as the default route
  pkg/console/controllers/route/controller.go
  pkg/console/controllers/route/controller_test.go
  pkg/console/subresource/route/route.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#429 Bug 1835551: Inject proxy envars to console-operator deployment
  manifests/07-operator.yaml
  pkg/console/controllers/route/controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#427 Bug 1835221: Sync loop should error out on resources that depend on route that is not admitted
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/route/controller.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/route/route.go
  pkg/console/subresource/route/route_test.go
  test/e2e/downloads_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#432 Bug 1839621: Grant Console SA permissions to read webhooks configurations
  manifests/03-rbac-role-cluster.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test
