Repository openshift/console-operator, pull requests merged in 2020-02, with the labels that each got.

#376 Bug 1794548: IPv6 support to console operator & console [openshift-4.3.z]
  manifests/05-config.yaml
  manifests/07-downloads-deployment.yaml
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/config_merger_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#377 Bug 1798315: Console operator should provide valid gitCommit and gitVersion versions
  pkg/console/version/version.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#381 Bug 1777486: Add monitoring-shared-config and logging-shared-config configmaps from openshift-config-managed to the console-config
  pkg/api/api.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/types.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
