Repository openshift/console-operator, pull requests merged in 2020-12, with the labels that each got.

#488 Annotate manifests for single-node-developer cluster profile
  manifests/0000_90_console-operator_01_prometheusrbac.yaml
  manifests/0000_90_console-operator_02_servicemonitor.yaml
  manifests/01-helm.yaml
  manifests/01-oauth.yaml
  manifests/01-operator-config.yaml
  manifests/02-namespace.yaml
  manifests/03-rbac-role-cluster-extensions.yaml
  manifests/03-rbac-role-cluster.yaml
  manifests/03-rbac-role-ns-console.yaml
  manifests/03-rbac-role-ns-openshift-config-managed.yaml
  manifests/03-rbac-role-ns-openshift-config.yaml
  manifests/03-rbac-role-ns-openshift-console-user-settings.yaml
  manifests/03-rbac-role-ns-operator.yaml
  manifests/04-rbac-rolebinding-cluster.yaml
  manifests/04-rbac-rolebinding.yaml
  manifests/05-config-public.yaml
  manifests/05-config.yaml
  manifests/05-service.yaml
  manifests/06-sa.yaml
  manifests/07-downloads-deployment.yaml
  manifests/07-downloads-helm.yaml
  manifests/07-downloads-route.yaml
  manifests/07-downloads-service.yaml
  manifests/07-operator.yaml
  manifests/08-clusteroperator.yaml
  manifests/09-console-link-openshift-blog.yaml
  manifests/09-console-link-openshift-learning-portal.yaml
Labels: approved, lgtm

#491 Add ROKS profile annotation to recently added manifests
  manifests/02-namespace.yaml
  manifests/03-rbac-role-ns-openshift-console-user-settings.yaml
Labels: approved, lgtm

#489 Bump(api) to get HelmChartRepository changes
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/helm/v1beta1/0000_10-helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/types_helm.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/register.go
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/oauth/v1/types.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#490 CONSOLE-2472: Add initial quick starts
  Dockerfile.rhel7
  README.md
  quickstarts/README.md
  quickstarts/add-healthchecks-quickstart.yaml
  quickstarts/explore-pipeline-quickstart.yaml
  quickstarts/explore-serverless-quickstart.yaml
  quickstarts/monitor-sampleapp-quickstart.yaml
  quickstarts/sample-application-quickstart.yaml
Labels: approved, lgtm

#494 Update Serverless Quick Start
  quickstarts/explore-serverless-quickstart.yaml
Labels: approved, lgtm

#495 Bug 1906798: Export operator dev catalog customization to console-config ConfigMap
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/types.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm

#496 Bug 1906713: Logged user should be able to get consolequickstarts
  manifests/03-rbac-role-cluster-extensions.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#492 Bug 1907280: Adds quickstart for ocs install tour
  quickstarts/ocs-install-tour-quickstart.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#483 Bug 1894216: Improve OpenShift Console availability
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
