Repository openshift/console-operator, pull requests merged in 2020-09, with the labels that each got.

#466 Bug 1875969: clidownloads: IBM Power and Z are supported
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/clidownloads/controller_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#458 Bug 1872375: Add RedHat Helm chart repository as default repo in OCP payload
  manifests/01-helm.yaml
  manifests/03-rbac-role-cluster.yaml
  manifests/04-rbac-rolebinding-cluster.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#443 [release-4.4] Bug 1847323: Publish license file
  manifests/07-downloads-deployment.yaml
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/clidownloads/controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#471 Bug 1880307: Fix inconsistent vendoring in vendor/modules.txt
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#475 Bug 1883461: Upgrade to klog v2
  go.mod
  go.sum
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/resourcesyncdestination/controller.go
  pkg/console/controllers/route/controller.go
  pkg/console/controllers/service/controller.go
  pkg/console/metrics/metrics.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/status/status.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/route/route.go
  pkg/console/subresource/util/util.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
