Repository openshift/console-operator, pull requests merged in 2020-03, with the labels that each got.

#385 Bug 1809665: The console should wait until it is out of rotation to shut down
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#384 Bug 1806787: Expose openshift_console_operator_build_info metric
  pkg/console/metrics/console_url.go
  pkg/console/metrics/metrics.go
  pkg/console/metrics/register.go
  pkg/console/operator/operator.go
  pkg/console/starter/starter.go
  pkg/console/version/version.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#382 Add Helm and HelmChartRepo types
  pkg/console/subresource/consoleserver/types.go
Labels: approved, lgtm, size/XS

#383 Bug 1777486: Update the monitoring and logging URLs name
  pkg/api/api.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/types.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#389 [release-4.4] Bug 1804884: Add monitoring-shared-config configmaps from openshift-config-managed to the console-config
  pkg/api/api.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/types.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#393 Update oc clidownload cr to indicate that certain builds are unsupported
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/clidownloads/controller_test.go
Labels: approved, lgtm, size/S

#392 Bump DEFAULT_DOC_URL for okd & ocp
  pkg/console/subresource/configmap/brand_ocp.go
  pkg/console/subresource/configmap/brand_okd.go
Labels: approved, lgtm, size/XS

#396 Sync operands status in clidownloads controller
  pkg/console/controllers/clidownloads/controller.go
Labels: approved, lgtm

#395 Route controller
  pkg/console/controllers/route/controller.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
Labels: approved, lgtm

#399 Status handling for RouteHealth
  pkg/console/controllers/route/controller.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
Labels: approved, lgtm

#400 Remove duplicit imports
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm
