Repository openshift/console-operator, pull requests merged in 2020-04, with the labels that each got.

#403 Fix console oauthEndpointCAFile setting
  pkg/console/operator/sync_v400.go
Labels: approved, lgtm

#410 Add 'make test-unit' to autocomplete
  Makefile
Labels: approved, lgtm

#411 Update OWNERS file with component
  OWNERS
Labels: approved, lgtm

#408 Remove "Technology Preview" reference from Helm CLI download description
  manifests/07-downloads-helm.yaml
Labels: approved, lgtm

#402 Custom console route
  manifests/03-rbac-role-cluster.yaml
  manifests/03-rbac-role-ns-console.yaml
  manifests/03-rbac-role-ns-openshift-config.yaml
  pkg/api/api.go
  pkg/console/controllers/route/controller.go
  pkg/console/controllers/route/controller_test.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/route/route.go
  pkg/console/subresource/route/route_test.go
Labels: approved, lgtm

#417 Bug 1826042: Missing 'Learning Portal' and 'OpenShift Blog' links from the console help menu
  manifests/09-console-link-openshift-blog.yaml
  manifests/09-console-link-openshift-learning-portal.yaml
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#418 Bug 1826628: Delete custom route after it is unset from console operator config
  pkg/console/controllers/route/controller.go
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#413 Bug 1826716: RBAC to authorise service account to list CRDs
  manifests/03-rbac-role-cluster.yaml
  manifests/04-rbac-rolebinding-cluster.yaml
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#419 Bug 1828272: Update 'Learning Portal' console helpMenu url to track where request it is coming from
  manifests/09-console-link-openshift-learning-portal.yaml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#415 Bug 1826046: declare correct container port in console pod spec
  pkg/console/subresource/deployment/deployment.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
