Repository openshift/console-operator, pull requests merged in 2021-05, with the labels that each got.

#539 Bug 1956610: Add missing cluster profile annotations to manage-helm-repos quickstart manifest
  quickstarts/manage-helm-repos.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#531 Bug 1948524: Update operator's status with downloads deployment generation && pull route health check into a standalone controller
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/downloadsdeployment/controller.go
  pkg/console/controllers/healthcheck/controller.go
  pkg/console/controllers/route/controller.go
  pkg/console/controllers/service/controller.go
  pkg/console/operator/operator.go
  pkg/console/starter/starter.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#542 Bug 1954866: Add necessary priority class to downloads
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#541 Bug 1957198: Remove misspelled console-operator condition
  pkg/console/controllers/downloadsdeployment/controller.go
  pkg/console/starter/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#544 Bug 1959696: Add warning log message when custom domain is configured on console-operator config
  pkg/console/controllers/route/controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#546 Bug 1960324: quickstarts: remove "spec.version"
  quickstarts/add-healthchecks-quickstart.yaml
  quickstarts/explore-pipeline-quickstart.yaml
  quickstarts/monitor-sampleapp-quickstart.yaml
  quickstarts/ocs-install-tour-quickstart.yaml
  quickstarts/sample-application-quickstart.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#543 CONSOLE-2768: Update the console public configmap manifests to use bindata
  bindata/configmaps/console-public-configmap.yaml
  manifests/05-config-public.yaml
  pkg/console/assets/bindata.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
Labels: approved, lgtm

#547 Bug 1960589: [release-4.7] quickstarts: remove "spec.version"
  quickstarts/add-healthchecks-quickstart.yaml
  quickstarts/explore-pipeline-quickstart.yaml
  quickstarts/monitor-sampleapp-quickstart.yaml
  quickstarts/ocs-install-tour-quickstart.yaml
  quickstarts/sample-application-quickstart.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#548 Bug 1962698: Console-operator can not create resource console-public configmap in the openshift-config-managed namespace
  manifests/03-rbac-role-ns-openshift-config-managed.yaml
  pkg/console/operator/sync_v400.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
