Repository openshift/console-operator, pull requests merged in 2021-06, with the labels that each got.

#545 Switching the URL of the default openshift helm repo.
  manifests/01-helm.yaml
Labels: approved, lgtm, ok-to-test

#552 Bug 1952405: Console operator should report Available:False when it's route is not accessible
  pkg/console/controllers/healthcheck/controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#554 Bug 1971690: clidownloads: ARM 64 is supported
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/clidownloads/controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#557 Bug 1975714: Add policy-group label to the openshift-console namespace manifest
  manifests/02-namespace.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#551 Bug 1966480: Console-operator's controllers are passed resourceSyncer which is not used
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/downloadsdeployment/controller.go
  pkg/console/controllers/healthcheck/controller.go
  pkg/console/controllers/route/controller.go
  pkg/console/controllers/service/controller.go
  pkg/console/starter/starter.go
  pkg/console/subresource/route/route.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
