Repository openshift/console-operator, pull requests merged in 2021-09, with the labels that each got.

#578 Bug 2000440: OCS Quick Start should not be shown unless you have proper privileges
  quickstarts/ocs-install-tour-quickstart.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#582 Bug 1989055: Revoke usage of Default Ingress Cert for console route healthcheck
  pkg/api/api.go
  pkg/console/controllers/healthcheck/controller.go
  pkg/console/controllers/route/controller.go
  pkg/console/starter/starter.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#581 Bug 2000768: Fix 4 Quick Starts
  quickstarts/add-healthchecks-quickstart.yaml
  quickstarts/monitor-sampleapp-quickstart.yaml
  quickstarts/node-with-s2i.yaml
  quickstarts/quarkus-with-s2i.yaml
  quickstarts/sample-application-quickstart.yaml
  quickstarts/spring-with-s2i.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#580 Bug 1994443: console-operator should report Available=true when at least available replica exists
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#585 Bug 2001240: Remove SimpleHTTP 'server' response header value
  pkg/console/subresource/deployment/deployment.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#590 Bug 1999314: Resync all controllers periodically
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/downloadsdeployment/controller.go
  pkg/console/controllers/healthcheck/controller.go
  pkg/console/controllers/route/controller.go
  pkg/console/controllers/service/controller.go
  pkg/console/operator/operator.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#589 [release-4.8] Bug 2003639: Use kubernetes.io/hostname for workload anti-affi… …nity
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved

#550 CONSOLE-2768: Update default and download deployments to use bindata
  bindata/deployments/console-deployment.yaml
  bindata/deployments/downloads-deployment.yaml
  pkg/console/assets/bindata.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  test/e2e/deployment_replicas_test.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved
