Repository openshift/console-operator, pull requests merged in 2021-02, with the labels that each got.

#502 Improvements to the Install Serverless Operator quick start
  quickstarts/explore-serverless-quickstart.yaml
  quickstarts/install-serverless.yaml
Labels: approved, lgtm

#503 fix consistency issues with QS displaynames and incorporate highlight…
  quickstarts/add-healthchecks-quickstart.yaml
  quickstarts/explore-pipeline-quickstart.yaml
  quickstarts/install-serverless.yaml
  quickstarts/manage-helm-repos.yaml
  quickstarts/monitor-sampleapp-quickstart.yaml
  quickstarts/ocs-install-tour-quickstart.yaml
  quickstarts/quarkus-with-s2i.yaml
  quickstarts/sample-application-quickstart.yaml
Labels: approved, lgtm

#504 RetryOnConflict should be fetching latest version of console-operator config
  test/e2e/custom_url_test.go
  test/e2e/plugins_test.go
  test/e2e/providers_test.go
Labels: approved, lgtm

#507 Bump polling interval when checking for resource unavailability
  test/e2e/framework/framework.go
Labels: approved, lgtm

#506 CONSOLE-2757: Bump github.com/openshift/api
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/modules.txt
Labels: approved, docs-approved, lgtm, px-approved, qe-approved

#500 CONSOLE-2366: Move the operator's controllers to lib-go controller factory
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/resourcesyncdestination/controller.go
  pkg/console/controllers/route/controller.go
  pkg/console/controllers/service/controller.go
  pkg/console/controllers/util/util.go
  pkg/console/operator/operator.go
  pkg/console/starter/starter.go
Labels: approved, docs-approved, lgtm, px-approved, qe-approved

#509 Bug 1931760: Non-unified reference to OCS in quickstarts
  quickstarts/explore-pipeline-quickstart.yaml
  quickstarts/install-serverless.yaml
  quickstarts/ocs-install-tour-quickstart.yaml
  quickstarts/sample-application-quickstart.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#508 CONSOLE-2526: Update console operator for single-node clusters
  manifests/07-downloads-deployment.yaml
  manifests/07-operator.yaml
  pkg/api/api.go
  pkg/console/controllers/downloadsdeployment/controller.go
  pkg/console/controllers/route/controller.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/util/util.go
  pkg/console/subresource/util/util_test.go
  test/e2e/framework/framework.go
Labels: approved, docs-approved, lgtm, px-approved, qe-approved
