Repository openshift/console-operator, pull requests merged in 2021-07, with the labels that each got.

#560 Bug 1975379: Use hard requirement for anti-affinity rules on both console's deployments
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#564 fix: Update the Node.js quickstart example repo.
  quickstarts/node-with-s2i.yaml
Labels: approved, lgtm, ok-to-test

#566 Bug 1975379: Only use `kubernetes.io/hostname` for workload anti-affinity
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#563 Rename Monitoring tab to Observe tab in monitoring sampleapp quickstart
  quickstarts/monitor-sampleapp-quickstart.yaml
Labels: approved, lgtm

#562 Remove references to upstream UI components and config
  pkg/api/api.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/types.go
Labels: approved, lgtm

#568 pkg/console/subresource/route: Drop GetCanonicalHost and IsAdmitted
  go.sum
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/healthcheck/controller.go
  pkg/console/controllers/route/controller.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/route/route.go
  pkg/console/subresource/route/route_test.go
  test/e2e/downloads_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/github.com/openshift/library-go/pkg/route/routeapihelpers/routeapihelpers.go
  vendor/modules.txt
Labels: approved, lgtm

#559 Adds ODF install tour
  quickstarts/install-odf.yaml
  quickstarts/ocs-install-tour-quickstart.yaml
Labels: approved, lgtm

#533 reduce initial steps to setup project
  README.md
Labels: approved, lgtm
