Repository openshift/console-operator, pull requests merged in 2021-10, with the labels that each got.

#588 Bug 2009454: Change web terminal subscription permissions from get to list
  manifests/03-rbac-role-cluster.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#597 Bug 2008185: Console operator go.mod should use go 1.16 version
  go.mod
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#599 Fast-forward
  bindata/deployments/console-deployment.yaml
  bindata/deployments/downloads-deployment.yaml
  pkg/console/assets/bindata.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  test/e2e/deployment_replicas_test.go
Labels: lgtm, approved
