Repository openshift/console-operator, pull requests merged in 2021-03, with the labels that each got.

#511 Bug 1935541: Check for error when generating default and user-defined config for the console-config configmap
  pkg/console/subresource/configmap/configmap.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#515 Bug 1937627: Bump DEFAULT_DOC_URL for 4.8
  pkg/console/subresource/configmap/brand_ocp.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#510 Add e2e test to check correct deployment replicas, based on the Infrastructure config TopologyMode
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  test/e2e/deployment_replicas_test.go
  test/e2e/framework/clientset.go
  test/e2e/framework/framework.go
  test/e2e/plugins_test.go
Labels: approved, lgtm

#513 Add in get subscriptions to console service account
  manifests/03-rbac-role-cluster.yaml
Labels: approved, lgtm
