Repository openshift/console-operator, pull requests merged in 2021-11, with the labels that each got.

#607 Bug 2018380: Migrate docs links to access.redhat.com
  pkg/console/subresource/configmap/brand_ocp.go
  quickstarts/add-healthchecks-quickstart.yaml
  quickstarts/explore-pipeline-quickstart.yaml
  quickstarts/install-serverless.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#608 Bug 2013632: Correct grammar error in ODF quickstart
  quickstarts/install-odf.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#609 [release-4.9] Bug 2016028: Correction/Changes in Quick Start Guides for ODF
  quickstarts/install-odf.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#605 Bug 2016654: Use hard requirements for antiaffinity rules
  manifests/07-downloads-deployment.yaml
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#611 Bug 2021400: Bump documentationBaseURL to 4.10
  pkg/console/subresource/configmap/brand_ocp.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#596 [release-4.9] Bug 2008142: Change web terminal subscription permissions from get to list
  manifests/03-rbac-role-cluster.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed
