Repository openshift/console-operator, pull requests merged in 2022-10, with the labels that each got.

#676 ODC-6778: Bump openshift/api to get devcatalog disable types cuztomization changes
  go.mod
  go.sum
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/types.go
  vendor/github.com/openshift/api/.gitignore
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/config/v1alpha1/0000_10_config-operator_01_insightsdatagather.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/Makefile
  vendor/github.com/openshift/api/machine/v1/control-plane-machine-set.aws.stable.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/control-plane-machine-set.azure.stable.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/control-plane-machine-set.gcp.stable.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/control-plane-machine-set.stable.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/types_aws.go
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, qe-approved, px-approved, docs-approved

#677 CONSOLE-3125: Add cluster filtering by product and ocp version
  pkg/api/api.go
  pkg/console/controllers/managedclusters/controller.go
  pkg/console/controllers/managedclusters/controller_test.go
  pkg/console/controllers/util/util.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved

#688 update to release.openshift.io/feature-set to match OCP 4.12
  manifests/03-rbac-role-cluster.yaml
  manifests/04-rbac-rolebinding-cluster.yaml
Labels: lgtm, approved, bugzilla/valid-bug

#684 OCPBUGS-1708: Set i18n LoadType to Lazy when v1alpha1 i18n annotation is set to false
  pkg/cmd/crdconversionwebhook/converter/converter.go
  pkg/cmd/crdconversionwebhook/converter/converter_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#691 CONSOLE-3337: Dynamic plugin proxy reference issue
  pkg/cmd/crdconversionwebhook/converter/converter.go
  pkg/cmd/crdconversionwebhook/converter/converter_test.go
  pkg/console/subresource/configmap/configmap_test.go
Labels: lgtm, approved, bugzilla/valid-bug

#687 CONSOLE-3252: Create a ConsoleNotification when cluster is performing an upgrade
  manifests/03-rbac-role-cluster.yaml
  manifests/03-rbac-role-ns-operator.yaml
  pkg/api/api.go
  pkg/console/controllers/upgradenotification/controller.go
  pkg/console/starter/starter.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved
