Repository openshift/console-operator, pull requests merged in 2022-07, with the labels that each got.

#659 Bug 2021297: Pass RELEASE_VERSION envar into the console pod
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/types.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#657 Bug 2093852: InfrastructureTopology must be driving console affinity rule creation
  pkg/console/subresource/deployment/deployment.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#662 Bug 2055494: Distinguish between route conditions
  pkg/console/controllers/route/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#663 Bug 2089950: Deleting downloads deployment should not fail if already deleted
  pkg/console/controllers/downloadsdeployment/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
