Repository openshift/console-operator, pull requests merged in 2022-09, with the labels that each got.

#675 OCPBUGS-457: TestEditUnmanagedPodDisruptionBudget flakes
  test/e2e/removed_test.go
  test/e2e/util.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#665 CONSOLE-3220: Add console capability to all manifests
  manifests/0000_90_console-operator_01_prometheusrbac.yaml
  manifests/0000_90_console-operator_02_servicemonitor.yaml
  manifests/0000_90_console_01_prometheusrbac.yaml
  manifests/0000_90_console_02_servicemonitor.yaml
  manifests/01-helm.yaml
  manifests/01-oauth.yaml
  manifests/01-operator-config.yaml
  manifests/02-namespace.yaml
  manifests/03-rbac-role-cluster-extensions.yaml
  manifests/03-rbac-role-cluster.yaml
  manifests/03-rbac-role-ns-console.yaml
  manifests/03-rbac-role-ns-openshift-config-managed.yaml
  manifests/03-rbac-role-ns-openshift-config.yaml
  manifests/03-rbac-role-ns-openshift-console-user-settings.yaml
  manifests/03-rbac-role-ns-operator.yaml
  manifests/04-rbac-rolebinding-cluster.yaml
  manifests/04-rbac-rolebinding.yaml
  manifests/05-config.yaml
  manifests/05-service.yaml
  manifests/06-sa.yaml
  manifests/07-downloads-helm.yaml
  manifests/07-operator.yaml
  manifests/08-clusteroperator.yaml
  manifests/09-console-link-openshift-blog.yaml
  manifests/09-console-link-openshift-learning-portal.yaml
  quickstarts/add-healthchecks-quickstart.yaml
  quickstarts/explore-pipeline-quickstart.yaml
  quickstarts/install-helmchartrepo-ns.yaml
  quickstarts/install-odf.yaml
  quickstarts/install-serverless.yaml
  quickstarts/manage-helm-repos.yaml
  quickstarts/monitor-sampleapp-quickstart.yaml
  quickstarts/node-with-s2i.yaml
  quickstarts/ocs-install-tour-quickstart.yaml
  quickstarts/quarkus-with-helm.yaml
  quickstarts/quarkus-with-s2i.yaml
  quickstarts/sample-application-quickstart.yaml
  quickstarts/spring-with-s2i.yaml
Labels: lgtm, approved, ok-to-test, qe-approved, px-approved, docs-approved

#669 CONSOLE-3242: Heterogeneous architecture clusters
  manifests/03-rbac-role-cluster.yaml
  pkg/api/api.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/types.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved

#658 Bug 2100860: Retrieve user-defined Alertmanager services from shared configmap
  pkg/api/api.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/types.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#682 OCPBUGS-785: Bump documentationBaseURL to 4.12
  pkg/console/subresource/configmap/brand_ocp.go
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#683 CONSOLE-3069: Handle new v1 ConsolePlugin api in the operator
  pkg/api/api.go
  pkg/cmd/crdconversionwebhook/converter/converter.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  test/e2e/framework/clientset.go
  test/e2e/plugins_test.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved
