Repository openshift/console-operator, pull requests merged in 2022-04, with the labels that each got.

#642 Bug 2057696: Console operator should not block installation/upgrade process when set to Removed state
  pkg/console/operator/operator.go
  pkg/console/status/status.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#643 [release-4.8] Bug 2071200: Fix setting of custom cert for default route
  pkg/console/controllers/route/controller.go
  pkg/console/subresource/route/route.go
  test/e2e/custom_url_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#646 [release-4.10] Bug 2059992: Re-enable TestMetricsEndpoint e2e test case
  test/e2e/metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#648 Bug 2075478: Bump docs version to 4.11
  pkg/console/subresource/configmap/brand_ocp.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#650 Bug 2067155: Modify the operator display name to match it with the name displayed in operatorhub
  quickstarts/explore-pipeline-quickstart.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
