Repository openshift/console-operator, pull requests merged in 2022-01, with the labels that each got.

#622 Bug 2036937: Update download odo link to new mirror
  pkg/console/controllers/clidownloads/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#621 Bug 2030574: Console resources are using older 'service.alpha.openshift.io' annotation
  bindata/services/console-redirect-service.yaml
  bindata/services/console-service.yaml
  manifests/05-service.yaml
  pkg/console/assets/bindata.go
  pkg/console/subresource/configmap/service_ca.go
  test/e2e/util.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#620 Bug 2033434: clidownloads: add darwin/arm64 oc
  bindata/deployments/downloads-deployment.yaml
  pkg/console/assets/bindata.go
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/clidownloads/controller_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#623 Bug 2037635: Fix setting of custom cert for default route
  pkg/console/controllers/route/controller.go
  pkg/console/subresource/route/route.go
  test/e2e/custom_url_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#626 [release-4.9] Bug 2040275: Bump build-machinery-go for console-operator to pickup change in yaml-patch repository
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#627 [release-4.8] Bug 2041359: Bump build-machinery-go for console-operator to pickup change in yaml-patch repository
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#625 Add Jon Jackson to approvers list
  OWNERS
Labels: lgtm, approved, qe-approved, px-approved, docs-approved

#631 Add QS for installing namespeced Helm Chart Repos
  quickstarts/install-helmchartrepo-ns.yaml
Labels: lgtm, approved, qe-approved, px-approved, docs-approved

#629 [release-4.7] Bug 2042534: Bump build-machinery-go for console-operator to pickup change in yaml-patch repository
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#595 [release-4.8] Bug 2008141: Change web terminal subscription permissions from get to list
  manifests/03-rbac-role-cluster.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed
