Repository openshift/console-operator, pull requests merged in 2023-01, with the labels that each got.

#703 ACM-2360: Add more steps to host inventory quick start
  quickstarts/host-inventory-quickstart.yaml
Labels: lgtm, approved, tide/merge-method-squash, qe-approved, px-approved, docs-approved

#718 [release-4.11] OCPBUGS-5499: Add host inventory quickstart
  quickstarts/host-inventory-quickstart.yaml
Labels: lgtm, approved, tide/merge-method-squash, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug

#698 PD-1365: Add quickstart - Get started with multicluster engine
  quickstarts/install-multicluster-engine.yaml
Labels: lgtm, approved, ok-to-test, qe-approved, px-approved, docs-approved

#726 OCPBUGS-6520: Test if all tested resrouces are available before launching Unmanaged* e2e tests
  test/e2e/unmanaged_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
