Repository openshift/console-operator, pull requests merged in 2023-04, with the labels that each got.

#741 OCPBUGS-11071: Operator should not add empty strings node arch list i…
  pkg/console/operator/sync_v400.go
  pkg/console/operator/sync_v400_test.go
Labels: lgtm, approved, tide/merge-method-squash, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#706 OCPBUGS-4009: Console operator should report ConsolePlugins as relate…
  pkg/console/starter/starter.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#743 OCPBUGS-11164: Disable multicluster tech preview
  manifests/03-rbac-role-cluster.yaml
  manifests/04-rbac-rolebinding-cluster.yaml
  pkg/console/starter/starter.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/clientset.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/doc.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/cluster_client.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/clusterclaim.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/doc.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/generated_expansion.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/managedclusterset.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/managedclustersetbinding.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/placement.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/placementdecision.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/modules.txt
  vendor/open-cluster-management.io/cluster-proxy/pkg/generated/clientset/versioned/clientset.go
  vendor/open-cluster-management.io/cluster-proxy/pkg/generated/clientset/versioned/doc.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#749 Revert "OCPBUGS-11164: Disable multicluster tech preview"
  manifests/03-rbac-role-cluster.yaml
  manifests/04-rbac-rolebinding-cluster.yaml
  pkg/console/starter/starter.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/clientset.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/doc.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/cluster_client.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/clusterclaim.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/doc.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/generated_expansion.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/managedclusterset.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/managedclustersetbinding.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/placement.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/placementdecision.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/modules.txt
  vendor/open-cluster-management.io/cluster-proxy/pkg/generated/clientset/versioned/clientset.go
  vendor/open-cluster-management.io/cluster-proxy/pkg/generated/clientset/versioned/doc.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#742 CONSOLE-3279: Add node operating systems to console config
  pkg/api/api.go
  pkg/console/operator/sync_v400.go
  pkg/console/operator/sync_v400_test.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/types.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#751 OCPBUGS-11298: Disable multicluster tech preview
  manifests/03-rbac-role-cluster.yaml
  manifests/04-rbac-rolebinding-cluster.yaml
  pkg/console/starter/starter.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/clientset.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/doc.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/cluster_client.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/clusterclaim.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/doc.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/generated_expansion.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/managedclusterset.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/managedclustersetbinding.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/placement.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1alpha1/placementdecision.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/modules.txt
  vendor/open-cluster-management.io/cluster-proxy/pkg/generated/clientset/versioned/clientset.go
  vendor/open-cluster-management.io/cluster-proxy/pkg/generated/clientset/versioned/doc.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#753 OCPBUGS-11969: Changing field on any of routes in the openshift-console namespace wont trigger sync loop
  pkg/console/controllers/route/controller.go
  pkg/console/subresource/route/route.go
  test/e2e/util.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#755 OCPBUGS-12439: Add new PrometheusRule to collect metrics for cluster-monitoring-operator
  manifests/cluster-monitoring-prometheus-rules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, px-approved, docs-approved, jira/valid-bug, jira/valid-reference

#710 OCPBUGS-5059: Make enabled plugins unique
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/util/util.go
  pkg/console/subresource/util/util_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
