Repository openshift/console-operator, pull requests merged in 2023-11, with the labels that each got.

#810 CONSOLE-3613: Update vendor bundle after removing multicluster code
  go.mod
  go.sum
  vendor/github.com/open-cluster-management/api/LICENSE
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/scheme/doc.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/scheme/register.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1/cluster_client.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1/doc.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1/generated_expansion.go
  vendor/github.com/open-cluster-management/api/client/cluster/clientset/versioned/typed/cluster/v1/managedcluster.go
  vendor/github.com/open-cluster-management/api/cluster/v1/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml
  vendor/github.com/open-cluster-management/api/cluster/v1/doc.go
  vendor/github.com/open-cluster-management/api/cluster/v1/register.go
  vendor/github.com/open-cluster-management/api/cluster/v1/types.go
  vendor/github.com/open-cluster-management/api/cluster/v1/zz_generated.deepcopy.go
  vendor/github.com/open-cluster-management/api/cluster/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/open-cluster-management/api/cluster/v1alpha1/0000_00_clusters.open-cluster-management.io_managedclustersets.crd.yaml
  vendor/github.com/open-cluster-management/api/cluster/v1alpha1/0000_01_clusters.open-cluster-management.io_managedclustersetbindings.crd.yaml
  vendor/github.com/open-cluster-management/api/cluster/v1alpha1/0000_02_clusters.open-cluster-management.io_clusterclaims.crd.yaml
  vendor/github.com/open-cluster-management/api/cluster/v1alpha1/0000_03_clusters.open-cluster-management.io_placements.crd.yaml
  vendor/github.com/open-cluster-management/api/cluster/v1alpha1/0000_04_clusters.open-cluster-management.io_placementdecisions.crd.yaml
  vendor/github.com/open-cluster-management/api/cluster/v1alpha1/0001_02_clusters.open-cluster-management.io_clusterclaims.crd.yaml
  vendor/github.com/open-cluster-management/api/cluster/v1alpha1/doc.go
  vendor/github.com/open-cluster-management/api/cluster/v1alpha1/register.go
  vendor/github.com/open-cluster-management/api/cluster/v1alpha1/types.go
  vendor/github.com/open-cluster-management/api/cluster/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/open-cluster-management/api/cluster/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/modules.txt
  vendor/open-cluster-management.io/cluster-proxy/pkg/generated/clientset/versioned/typed/proxy/v1alpha1/doc.go
  vendor/open-cluster-management.io/cluster-proxy/pkg/generated/clientset/versioned/typed/proxy/v1alpha1/generated_expansion.go
  vendor/open-cluster-management.io/cluster-proxy/pkg/generated/clientset/versioned/typed/proxy/v1alpha1/managedproxyconfiguration.go
  vendor/open-cluster-management.io/cluster-proxy/pkg/generated/clientset/versioned/typed/proxy/v1alpha1/managedproxyserviceresolver.go
  vendor/open-cluster-management.io/cluster-proxy/pkg/generated/clientset/versioned/typed/proxy/v1alpha1/proxy_client.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#808 CONSOLE-3804: split oauthclient controller from the common logic
  manifests/03-rbac-role-cluster.yaml
  pkg/console/controllers/oauthclients/oauthclients.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference, acknowledge-critical-fixes-only

#813 TRT-1361: Revert #808 "CONSOLE-3804: split oauthclient controller from the common logic"
  manifests/03-rbac-role-cluster.yaml
  pkg/console/controllers/oauthclients/oauthclients.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference, acknowledge-critical-fixes-only

#806 ODC-7418: Add Janus IDP and RHDH Quick starts
  quickstarts/janus-idp-installation-via-helm.yaml
  quickstarts/janus-idp-installation-via-operator.yaml
  quickstarts/rhdh-installation-via-helm.yaml
  quickstarts/rhdh-installation-via-operator.yaml
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference, acknowledge-critical-fixes-only

#819 OCPBUGS-24203: ConsolePlugin metrics must no longer be grouped by the vendor
  manifests/cluster-monitoring-prometheus-rules.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
