Repository openshift/console-operator, pull requests merged in 2023-10, with the labels that each got.

#796 OCPBUGS-19080: Reset console operator's conditions
  go.mod
  go.sum
  pkg/console/operator/operator.go
  pkg/console/status/status.go
  vendor/modules.txt
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#793 [release-4.13] OCPBUGS-18972: Manual backport of #761
  pkg/api/api.go
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/starter/starter.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#801 HOSTEDCP-1250: remove redundant cert check
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/config_merger_test.go
  pkg/console/subresource/deployment/deployment.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#795 OCPVE-719: feat: add support for olm capability
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#802 OCPBUGS-21972: Disable HTTP/2 for webhook
  pkg/cmd/crdconversionwebhook/cmd.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#799 CONSOLE-3613: Remove multicluster code from console operator
  bindata/assets/managedclusteractions/console-create-oauth-client.yaml
  bindata/assets/managedclusterviews/console-oauth-client.yaml
  bindata/assets/managedclusterviews/console-oauth-server-cert.yaml
  bindata/assets/managedclusterviews/olm-config.yaml
  bindata/assets/managedserviceproxyresolvers/thanos-querier.yaml
  manifests/03-rbac-role-cluster.yaml
  pkg/api/api.go
  pkg/console/controllers/advancedclustermanagement/managedclusters/controller.go
  pkg/console/controllers/advancedclustermanagement/thanosquerierproxyserviceresolver/controller.go
  pkg/console/controllers/util/util.go
  pkg/console/controllers/util/util_test.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/api_server_ca.go
  pkg/console/subresource/configmap/api_server_ca_test.go
  pkg/console/subresource/configmap/managed_cluster_oauth_server_cert.go
  pkg/console/subresource/configmap/managed_clusters.go
  pkg/console/subresource/configmap/managed_clusters_test.go
  pkg/console/subresource/consoleserver/types.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/managedclusteraction/create_oauth_client.go
  pkg/console/subresource/managedclusterview/oauth_client.go
  pkg/console/subresource/managedclusterview/oauth_server_cert.go
  pkg/console/subresource/managedclusterview/olm_config.go
  pkg/console/subresource/managedserviceproxyresolver/apply.go
  pkg/console/subresource/managedserviceproxyresolver/thanos-querier.go
  pkg/console/subresource/util/util.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference
