Repository openshift/console-operator, pull requests merged in 2023-02, with the labels that each got.

#725 OCPBUGS-6488: Recover ConsoleNotificationSync after being degraded
  pkg/console/controllers/upgradenotification/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#723 OCPBUGS-4008: Add managed cluster config map resource version to cons…
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-low

#717 ACM-2781: Have operator as a prerequisite
  quickstarts/host-inventory-quickstart.yaml
Labels: lgtm, approved, qe-approved, px-approved, docs-approved

#730 OCPBUGS-5420: Back port on-premise host inventory quick start to OCP 4.12.z
  quickstarts/host-inventory-quickstart.yaml
  quickstarts/install-multicluster-engine.yaml
Labels: lgtm, approved, tide/merge-method-squash, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#732 OCPBUGS-5499: Back port on-premise host inventory quick start to OCP 4.11.x
  quickstarts/host-inventory-quickstart.yaml
  quickstarts/install-multicluster-engine.yaml
Labels: lgtm, approved, tide/merge-method-squash, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#727 OCPBUGS-5836: Incorrect redirection when user try to download windows oc binary
  bindata/deployments/downloads-deployment.yaml
  pkg/console/assets/bindata.go
Labels: lgtm, approved, tide/merge-method-squash, ok-to-test, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#734 OCPBUGS-2783: Distinguish between route conditions and remove the old ones
  pkg/console/controllers/route/controller.go
  pkg/console/starter/starter.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical, jira/valid-reference

#733 OCPBUGS-5893: Back port on-premise host inventory quick start to OCP 4.10
  quickstarts/host-inventory-quickstart.yaml
  quickstarts/install-multicluster-engine.yaml
Labels: lgtm, approved, tide/merge-method-squash, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
