Repository openshift/console-operator, pull requests merged in 2023-08, with the labels that each got.

#784 chore: manifests/09-console-link-*: Drop obsolete deletion manifests
  manifests/09-console-link-openshift-blog.yaml
  manifests/09-console-link-openshift-learning-portal.yaml
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#785 OCPBUGS-17424: Handle cache.DeletedFinalStateUnknown correctly
  pkg/console/controllers/util/util.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#786 OCPBUGS-17424: Really handle DeletedFinalStateUnknown correctly
  pkg/console/controllers/util/util.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#783 CONSOLE-3438: Switch to using assets
  Makefile
  bindata/assets.go
  bindata/assets/configmaps/console-configmap.yaml
  bindata/assets/configmaps/console-public-configmap.yaml
  bindata/assets/deployments/console-deployment.yaml
  bindata/assets/deployments/downloads-deployment.yaml
  bindata/assets/managedclusteractions/console-create-oauth-client.yaml
  bindata/assets/managedclusterviews/console-oauth-client.yaml
  bindata/assets/managedclusterviews/console-oauth-server-cert.yaml
  bindata/assets/managedclusterviews/olm-config.yaml
  bindata/assets/managedserviceproxyresolvers/thanos-querier.yaml
  bindata/assets/pdb/console-pdb.yaml
  bindata/assets/pdb/downloads-pdb.yaml
  bindata/assets/routes/console-custom-route.yaml
  bindata/assets/routes/console-redirect-route.yaml
  bindata/assets/routes/console-route.yaml
  bindata/assets/routes/downloads-custom-route.yaml
  bindata/assets/routes/downloads-route.yaml
  bindata/assets/services/console-redirect-service.yaml
  bindata/assets/services/console-service.yaml
  bindata/assets/services/downloads-service.yaml
  pkg/console/assets/bindata.go
  pkg/console/controllers/poddisruptionbudget/controller.go
  pkg/console/controllers/service/controller.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  pkg/console/subresource/managedclusteraction/create_oauth_client.go
  pkg/console/subresource/managedclusterview/oauth_client.go
  pkg/console/subresource/managedclusterview/oauth_server_cert.go
  pkg/console/subresource/managedclusterview/olm_config.go
  pkg/console/subresource/managedserviceproxyresolver/thanos-querier.go
  pkg/console/subresource/route/route.go
Labels: lgtm, approved, ok-to-test, qe-approved, px-approved, docs-approved, jira/valid-reference
