Repository openshift/console-operator, pull requests merged in 2024-04, with the labels that each got.

#865 CONSOLE-3910: Add quickstart to impersonate a system:admin user
  quickstarts/impersonate-user.yaml
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#882 OCPBUGS-31619: use InfrastructureTopology for clusters using external CP as the console deploys on the worker nodes
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  test/e2e/deployment_replicas_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#887 OCPBUGS-32400: base OIDC status updates on the ExternalOIDC feature gate
  manifests/07-operator-ibm-cloud-managed.yaml
  manifests/07-operator.yaml
  pkg/console/controllers/oidcsetup/oidcsetup.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#873 OCPBUGS-20466: Tighten console operator permissions for cluster operators
  manifests/03-rbac-role-cluster.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#790 OCPBUGS-20129: Fix triggering `upgradenotification` in the cluster installation time
  pkg/console/controllers/upgradenotification/controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#840 CONSOLE-3902: Add cli login commands to console configmap
  pkg/api/api.go
  pkg/console/controllers/clioidcclientstatus/controller.go
  pkg/console/controllers/oauthclientsecret/oauthclientsecret.go
  pkg/console/controllers/oidcsetup/oidcsetup.go
  pkg/console/controllers/util/util.go
  pkg/console/operator/operator.go
  pkg/console/starter/starter.go
  pkg/console/subresource/authentication/cluster.go
  pkg/console/subresource/authentication/cluster_test.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/types.go
  pkg/console/subresource/crd/authentications.go
  pkg/console/subresource/infrastructure/cluster.go
  pkg/console/subresource/util/util.go
Labels: lgtm, approved, tide/merge-method-squash, qe-approved, px-approved, docs-approved, jira/valid-reference

#889 CONSOLE-4014: Pass OCM organization ID and OCP cluster ID to console-config.yaml
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/deployment/telemeter-client.go
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#892 TRT-1623: Revert "Merge pull request #889 from jhadvig/CONSOLE-4014"
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/deployment/telemeter-client.go
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference
