Repository openshift/console-operator, pull requests merged in 2024-05, with the labels that each got.

#893 CONSOLE-4014: Pass OCM organization ID and OCP cluster ID to console-config.yaml
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/deployment/telemeter-client.go
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#894 [release-4.13] OCPBUGS-18674: Reset console operator's conditions
  pkg/console/operator/operator.go
  pkg/console/status/status.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#899 TRT-1664: Revert #895 "CONSOLE-4047: Console-operator should be internally using listers for fetching data"
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/healthcheck/controller.go
  pkg/console/controllers/route/controller.go
  pkg/console/controllers/service/controller.go
  pkg/console/controllers/upgradenotification/controller.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/operator/sync_v400_test.go
  pkg/console/starter/starter.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#896 OKD-214: Dockerfile: Add ARG TAGS=ocp
  Dockerfile.rhel7
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#900 OCPBUGS-33505: Add missing return statement to fix crash in healthcheck controller
  pkg/console/controllers/healthcheck/controller.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#901 CONSOLE-4047: Console-operator should be internally using listers for fetching data
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/healthcheck/controller.go
  pkg/console/controllers/route/controller.go
  pkg/console/controllers/service/controller.go
  pkg/console/controllers/upgradenotification/controller.go
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/operator/sync_v400_test.go
  pkg/console/starter/starter.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference, acknowledge-critical-fixes-only

#904 OCPBUGS-33715: Cache organization ID
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#902 OCPBUGS-31777: Updates message verbs to use %q where appropriate.
  pkg/cmd/crdconversionwebhook/converter/framework.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#871 AUTH-482: set required-scc for openshift workloads
  bindata/assets/deployments/console-deployment.yaml
  bindata/assets/deployments/downloads-deployment.yaml
  manifests/07-conversionwebhook-ibm-cloud-managed.yaml
  manifests/07-conversionwebhook.yaml
  manifests/07-operator-ibm-cloud-managed.yaml
  manifests/07-operator.yaml
  pkg/console/subresource/deployment/deployment_test.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference
