Repository openshift/console-operator, pull requests merged in 2024-12, with the labels that each got.

#940 OCPBUGS-44556: console/status: set initial value of Message field
  pkg/console/status/auth_status.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#942 OCPBUGS-44362: Remove the v1alpha1 schema for ConsolePlugin CRD
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins-Default.crd.yaml
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_olm.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/exp/maps/maps.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#945 OCPBUGS-44953: don't set current clients when no OIDC providers are configured
  pkg/console/controllers/clioidcclientstatus/controller.go
  pkg/console/controllers/oidcsetup/oidcsetup.go
  pkg/console/status/auth_status.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#944 OCPBUGS-45222: Dont disable console when authConfig type is set to None
  pkg/console/controllers/oauthclients/oauthclients.go
  pkg/console/controllers/oauthclientsecret/oauthclientsecret.go
  pkg/console/controllers/util/informers.go
  pkg/console/controllers/util/informers_test.go
  pkg/console/operator/sync_v400.go
  pkg/console/subresource/consoleserver/config_builder.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-low, jira/valid-reference
