Repository openshift/console-operator, pull requests merged in 2024-01, with the labels that each got.

#824 OCPBUGS-25618: Bump documentationBaseURL to 4.16
  pkg/console/subresource/configmap/brand_ocp.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#826 OCPBUGS-7656: Remove service ca controller annotation from console-redirect service.
  bindata/assets/services/console-redirect-service.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#834 OCPBUGS-24041: Prevent healthcheck controller from Available=False blipping
  pkg/console/controllers/healthcheck/controller.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#830 NO-JIRA:(chore) remove unused loglevel
  manifests/07-operator-ibm-cloud-managed.yaml
  manifests/07-operator.yaml
Labels: lgtm, kind/cleanup, approved, ok-to-test, qe-approved, px-approved, docs-approved, jira/valid-reference

#838 OCPBUGS-27335: The console-deployment should set the number of replicas based on the ControlPlaneTopology
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  test/e2e/deployment_replicas_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#848 OCPBUGS-25484: make it impossible double set conditions in a single loop
  go.mod
  go.sum
  pkg/console/controllers/oauthclients/oauthclients.go
  pkg/console/status/auth_status.go
  pkg/console/status/status.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#851 [4.15] pick of OCPBUGS-27221: make it impossible double set conditions in a single loop
  go.mod
  go.sum
  pkg/console/controllers/oauthclients/oauthclients.go
  pkg/console/status/status.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#842 CONSOLE-3912: Merge auth cert configmap deployment annotations into one
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#841 OCPBUGS-27335: use InfrastructureTopology for clusters using external CP as the console deploys on the worker nodes
  pkg/console/subresource/deployment/deployment.go
  pkg/console/subresource/deployment/deployment_test.go
  test/e2e/deployment_replicas_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#849 CONSOLE-3912: OIDC: setup the volume name properly when custom CA is configured
  pkg/console/subresource/deployment/deployment.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#807 OCPBUGS-22681: Bump documentationBaseURL to 4.15
  pkg/console/subresource/configmap/brand_ocp.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
