Repository openshift/console-operator, pull requests merged in 2024-07, with the labels that each got.

#914 OCPBUGS-29547: Apply hypershift cluster-profile for ibm-cloud-managed
  manifests/07-operator.yaml
  quickstarts/consolequickstart-install-cryostat.yaml
  quickstarts/impersonate-user.yaml
  quickstarts/install-helmchartrepo-ns.yaml
  quickstarts/install-serverless.yaml
  quickstarts/jboss-eap7-with-helm.yaml
  quickstarts/manage-helm-repos.yaml
  quickstarts/node-with-s2i.yaml
  quickstarts/quarkus-with-helm.yaml
  quickstarts/quarkus-with-s2i.yaml
  quickstarts/spring-with-s2i.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#915 TRT-1733: Revert #914 "OCPBUGS-29547: Apply hypershift cluster-profile for ibm-cloud-managed"
  manifests/07-operator.yaml
  quickstarts/consolequickstart-install-cryostat.yaml
  quickstarts/impersonate-user.yaml
  quickstarts/install-helmchartrepo-ns.yaml
  quickstarts/install-serverless.yaml
  quickstarts/jboss-eap7-with-helm.yaml
  quickstarts/manage-helm-repos.yaml
  quickstarts/node-with-s2i.yaml
  quickstarts/quarkus-with-helm.yaml
  quickstarts/quarkus-with-s2i.yaml
  quickstarts/spring-with-s2i.yaml
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#913 OCPBUGS-33715: Cache organization ID when the ID changes
  pkg/console/operator/sync_v400.go
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#918 OCPBUGS-33715: Add logging for determining the ORG_ID source
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#916 [release-4.16] OCPBUGS-34012: Cache organization ID
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#919 OCPBUGS-36213: Bump openshift/api to pick up removal of conversion webhook server reference
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins.crd.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machineset.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers.crd.yaml
  vendor/modules.txt
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#912 OCPBUGS-35941: Bump documentationBaseURL to 4.17
  pkg/console/subresource/configmap/brand_ocp.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#920 CONSOLE-4161: Add Capabilities to config builder
  go.mod
  go.sum
  manifests/01-operator-config.yaml
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/types.go
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_console_01_consoles.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference
