Repository openshift/console-operator, pull requests merged in 2024-08, with the labels that each got.

#921 CONSOLE-4163: Add RBAC for console to GET PackageManifests
  manifests/03-rbac-role-cluster.yaml
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#925 OCPBUGS-38549: Get externalOrganizationID instead of the organizationID
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#924 OCPBUGS-37408:set required-scc for openshift workloads
  bindata/assets/deployments/console-deployment.yaml
  bindata/assets/deployments/downloads-deployment.yaml
  manifests/07-operator-ibm-cloud-managed.yaml
  manifests/07-operator.yaml
  pkg/console/subresource/deployment/deployment_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
