Repository openshift/console-operator, pull requests merged in 2025-08, with the labels that each got.

#1032 OCPBUGS-60219: make console operator responsible for creating oauth client
  manifests/01-oauth.yaml
  manifests/03-rbac-role-cluster.yaml
  pkg/console/controllers/oauthclients/oauthclients.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1018 CONSOLE-4665: Vendor ConsolePluginCRD v1alpha1 changes
  go.mod
  go.sum
  vendor/github.com/openshift/api/.golangci.yaml
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/apps/v1/generated.proto
  vendor/github.com/openshift/api/apps/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1alpha1/types_backup.go
  vendor/github.com/openshift/api/config/v1alpha1/types_cluster_monitoring.go
  vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
  vendor/github.com/openshift/api/console/v1/types_console_plugin.go
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins.crd.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machinehealthcheck.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machineset.go
  vendor/github.com/openshift/api/machine/v1beta1/types_provider.go
  vendor/github.com/openshift/api/networkoperator/v1/generated.proto
  vendor/github.com/openshift/api/networkoperator/v1/types_egressrouter.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/types_etcdbackup.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/samples/v1/generated.proto
  vendor/github.com/openshift/api/samples/v1/types_config.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/sharedresource/v1alpha1/types_shared_configmap.go
  vendor/github.com/openshift/api/sharedresource/v1alpha1/types_shared_secret.go
  vendor/github.com/openshift/api/template/v1/generated.proto
  vendor/github.com/openshift/api/template/v1/types.go
  vendor/modules.txt
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#1034 OCPBUGS-58094: Consolidate telemetry values oscilation
  pkg/console/telemetry/telemetry.go
  pkg/console/telemetry/telemetry_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1010 NO-JIRA: Fix typos in RHDH Quickstarts
  quickstarts/rhdh-installation-via-helm.yaml
  quickstarts/rhdh-installation-via-operator.yaml
Labels: lgtm, approved, tide/merge-method-squash, qe-approved, px-approved, docs-approved, jira/valid-reference
