Repository openshift/console-operator, pull requests merged in 2025-04, with the labels that each got.

#973 ART-12521: update go mod dependency for konflux
  .gitignore
  vendor/golang.org/x/sys/unix/dev_aix_ppc.go
  vendor/golang.org/x/sys/unix/dev_aix_ppc64.go
  vendor/golang.org/x/sys/unix/dev_zos.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#974 CONSOLE-4481: Add junit generation for unit and e2e testing
  Makefile
  test-e2e.sh
  test-unit.sh
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#971 OCPBUGS-45514: Report email_domain to telemetry
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#975 CONSOLE-4481: Add additional CSP test
  test-e2e.sh
  test/e2e/plugins_test.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#955 NETOBSERV-2023: Implement a quickstart for netobserv operator
  quickstarts/install-netobserv.yaml
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference, acknowledge-critical-fixes-only

#976 CONSOLE-4523: Add rhel8 and rhel9 oc binaries for Linux OS in CLI downloads
  bindata/assets/deployments/downloads-deployment.yaml
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/clidownloads/controller_test.go
  test/e2e/downloads_test.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference

#979 OCPBUGS-55082: Revert "Add rhel8 and rhel9 oc binaries for Linux OS in CLI downloads"
  bindata/assets/deployments/downloads-deployment.yaml
  pkg/console/controllers/clidownloads/controller.go
  pkg/console/controllers/clidownloads/controller_test.go
  test/e2e/downloads_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#977 ODC-7780: update quick starts to work in the converged perspective
  quickstarts/add-healthchecks-quickstart.yaml
  quickstarts/install-helmchartrepo-ns.yaml
  quickstarts/jboss-eap7-with-helm.yaml
  quickstarts/manage-helm-repos.yaml
  quickstarts/monitor-sampleapp-quickstart.yaml
  quickstarts/node-with-s2i.yaml
  quickstarts/quarkus-with-helm.yaml
  quickstarts/quarkus-with-s2i.yaml
  quickstarts/rhdh-installation-via-helm.yaml
  quickstarts/rhdh-installation-via-operator.yaml
  quickstarts/sample-application-quickstart.yaml
  quickstarts/spring-with-s2i.yaml
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-reference
