Repository openshift/console-operator, pull requests merged in 2025-02, with the labels that each got.

#957 OCPBUGS-46513: Add ConsolePluginContentSecurityPolicy feature gate to…
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/starter/starter.go
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/types.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#956 OCPBUGS-48536: Bump documentationBaseURL to 4.19
  pkg/console/subresource/configmap/brand_ocp.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-low, jira/valid-reference, acknowledge-critical-fixes-only

#954 ODC-7721: Disable developer perspective by default
  manifests/01-operator-config.yaml
  pkg/console/subresource/configmap/configmap_test.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/config_builder_test.go
  pkg/console/subresource/consoleserver/config_merger_test.go
  pkg/console/subresource/consoleserver/types.go
Labels: lgtm, approved, tide/merge-method-squash, qe-approved, px-approved, docs-approved, jira/valid-reference

#950 OCPBUGS-45514: Report email_domain to telemetry
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#961 OCPBUGS-51156: Revert #950 "OCPBUGS-45514: Report email_domain to telemetry"
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#962 OCPBUGS-45514: Report email_domain to telemetry + fix panic for uninitialized mail value.
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#964 OCPBUGS-51379: Re-revert Report email_domain to telemetry + fix panic for uninitialized mail value.
  pkg/console/operator/operator.go
  pkg/console/operator/sync_v400.go
  pkg/console/telemetry/telemetry.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-bug, jira/valid-reference
