Repository openshift/console-operator, pull requests merged in 2025-05, with the labels that each got.

#984 OCPBUGS-55698: Lift FeatureGate by bumping openshift/api
  go.mod
  go.sum
  test-e2e.sh
  test/e2e/plugins_test.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins-Default.crd.yaml
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins.crd.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#980 OCPBUGS-43792: Add plugins order to console config
  pkg/console/subresource/configmap/configmap.go
  pkg/console/subresource/consoleserver/config_builder.go
  pkg/console/subresource/consoleserver/types.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#990 OCPBUGS-52556: Revert v1alpha1 removal
  go.mod
  go.sum
  vendor/github.com/openshift/api/.golangci.yaml
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins.crd.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#991 [release-4.19] OCPBUGS-56761: Revert v1alpha1 removal
  go.mod
  go.sum
  vendor/github.com/openshift/api/.golangci.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/zz_generated.crd-manifests/90_consoleplugins.crd.yaml
  vendor/github.com/openshift/api/features.md
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
